### ISSUE TITLE
Cannot right click Aubergine to harvest

### ISSUE THREAD

**Issue by aaronhowser1** [MysticMods/MysticalWorld#100]
Basically #31. This is using `mysticalworld-1.14.4-1.6.10`.

**Comment by duely** [comment]
You'll need to actually install a mod that does right-click harvest. #31 was simply the cross-mod communication not working properly -- Mystical World has never actually included right-click harvest.

**Comment by aaronhowser1** [comment]
Well I can right click Wheat to harvest it, just not Aubergine. I don't know specifically what mod it is that adds it though.
