### ISSUE TITLE
Tool and armor recycling un-available

### ISSUE THREAD

**Issue by Sos339** [MysticMods/MysticalWorld#101]
The furnace recipes for smelting down used tools and armor into their nugget form is unavailable for **vanilla** items

https://i.imgur.com/J3wGQYs.png
Expected

https://i.imgur.com/yH9eaym.png
Result

***

### Environment Versions
Minecraft 1.14.4
forge-1.14.4-28.1.87
mysticallib-1.14.4-1.8.0
mysticalworld-1.14.4-1.6.10

(other mods are seen in pictures but bear no weight to the bug)
***

Log
https://gist.githubusercontent.com/Sos339/2816eaa4eb4481f95243e52fde307d17/raw/9f327fad6eb4cb91c63d8f0436ea8eb1f60145b8/latestlog

**Comment by EpicSquid** [comment]
Can you explain why other mods bare no weight to the bug?

**Comment by Sos339** [comment]
I had multiple mods installed when the bug first occurred however isolating mysticalworld (and core/lib) by itself, the bug still persists

**Comment by duely** [comment]
Your result picture, btw, is rather confusing as it seems to show the JEI uses of a golden sword rather than the furnace. However, I'm looking into it.

**Comment by Sos339** [comment]
Yea I could of worded it better and maybe screenshot it better too, its been a while since I did a github report
It was the first idea that came to mind instead of "it doesn't smelt"
https://i.imgur.com/0RnPbSv.png

**Comment by duely** [comment]
This should've been fixed in the most recent release.
