### ISSUE TITLE
Crashing when trying to use it on Enigmatica 2 modpack - MC version 1.12

### ISSUE THREAD

**Issue by EduManke** [MysticMods/MysticalWorld#102]
Tried to install MystWorld (1.5.0) to use with Roots 3 (3.0.21) and it crashes on the startup of the Enigmatica 2 modpack, the problem is not ocasionated by Roots 3, I removed R3 from the mod folder and it crashes without him, I am using MystLib (1.4.0)

**Comment by Birgliss** [comment]
could you post a crashlog?

**Comment by duely** [comment]
You'll need to make sure that you also update Forge to 2847, if it isn't already. That seems to be the most logical cause at this stage.

**Comment by Davoleo** [comment]
Duplicate of https://github.com/MysticMods/Roots/issues/358
