### ISSUE TITLE
tools recipes dictionary use.

### ISSUE THREAD

**Issue by frakier** [MysticMods/MysticalWorld#103]
USING THE 1.14.4 MOD

**Describe your suggestion:**

The recipe for your tools and armor uses mystical world copper, you should add the mystical world copper ingot {or dust or nugget} to the forge dictionary and then use the forge directory entry for the item recipes. This way any mod that adds a copper ingot {or dust or nugget} can be used to create you tools. [same recommendation for amethyst and all you other metals]
NOTE: You did this wit the Glistering Horn.

**Describe alternatives you've considered:**

I am fixing this using crafttweaker script for now.

**Additional context:**

**Comment by duely** [comment]
Thanks for that, I honestly thought I'd done that when I converted the recipes but I must've messed up.

**Comment by duely** [comment]
I've fixed this in the code, I'll aim to have a new release out soonish.

**Comment by duely** [comment]
This should've been fixed in the 1.6.12 release. (1.6.11 was an internal that never got released.)

**Comment by frakier** [comment]
using 
forge-1.14.4-28.1.102
mysticalmachinery-1.14.4-1.0.1.jar
mysticallib-1.14.4-1.10.0.jar
mysticalworld-1.14.4-1.6.12.jar
[various other mods]...
the recipes for the items still use the mods ingot [does not accept ingots of copper from another mod, registered as forge ingots of course]

**Comment by duely** [comment]
So apparently I forgot to regenerate the resources before doing the release; I changed the code but not the actual generated resources... will sort this out shortly.

**Comment by noobanidus** [comment]
This'll be in the release today
