### ISSUE TITLE
No plugins.yml folder in jar ?

### ISSUE THREAD

**Issue by mostwantedpwnz** [MysticMods/MysticalWorld#104]
I'm trying to install it on the server but says plugins.yml isn't in the jar

Is this only for single player ?

**Comment by duely** [comment]
This is for Forge, it's not a Sponge, SpongeForge, Paper, etc, plug-in.

**Comment by duely** [comment]
I think you must be doing something horribly wrong. [Plugins.yml appears to be related to Bukkit and Spigot related topics](https://www.google.com/search?q=plugins.yml+minecraft), whereas this mod is for Forge.

Does your server support Forge? I would recommend contacting your server, as this isn't something we can help you with.
