### ISSUE TITLE
[1.12.2] no crafting recipes for fence gates

### ISSUE THREAD

**Issue by cybercatgurrl** [MysticMods/MysticalWorld#105]
I'm on 1.12.2 and there are no recipes for the fence gates. The charred and mud block fence gates are in JEI but I cannot craft them. Not sure if bug reports from 1.12.2 are still welcome or not.

**Comment by duely** [comment]
1.12 reports are definitely appreciate, just make sure that you mark it as being 1.12!

I've been slowly working on fixing the subtitles issues that we currently have (where silkworms use the sounds of endermites and therefore the subtitles of endermites), so I was planning a new release. I'll make sure fence gate recipes get in!

**Comment by cybercatgurrl** [comment]
Thank you!
