### ISSUE TITLE
Crash with silent gems and mystical world ? - Rendering screen

### ISSUE THREAD

**Issue by gilles33377** [MysticMods/MysticalWorld#108]
Hello,

I have a problem : When i use silent gems and mystical world together on a server (only), the client crash when we "convert" a flower  to "dye" from inventory. ( flower from silent gems).
Here is a crash report.

Any idea ?

Thanks 
[crash-2019-12-08_20.43.22-client.txt](https://github.com/MysticMods/MysticalWorld/files/3937100/crash-2019-12-08_20.43.22-client.txt)

**Comment by noobanidus** [comment]
This is one of those annoying bugs that seems to crop up. I can't remember exactly what causes it, but Pyrotech had a similar issue: https://github.com/codetaylor/pyrotech/issues/12

As the recipe is on their end I'd recommend reporting this to Silent's Gems or seeing if it has already been reported there. I'm not sure what in Mystical World could be causing it.

**Comment by gilles33377** [comment]
After some research, i can see two possibilities :
- The "patchouli" Mod that MW depend.
- If the mod use "structurize", It can crash the game too.

**Comment by noobanidus** [comment]
Well, file issues with those; we don't use Structurize at all.
