### ISSUE TITLE
Allow Waterlogging of the Wet Mud Block

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#110]
**Describe your suggestion:**

Allow waterlogging of the Wet Mud Block, which makes sense since it has water in it.

**Comment by VulpTheHorseDog** [comment]
Do you mean waterlogging of the wet mud, or dry mud into wet? I couldn't see either having many uses.

**Comment by noobanidus** [comment]
Wet mud is slightly shorter than a normal block, so I can understand the point of waterlogging.

**Comment by VulpTheHorseDog** [comment]
Oh, why's it shorter?

**Comment by WenXin20** [comment]
I was thinking that it could actually be used in farms to hide water, since the block itself is slightly below the water block hieght.

And I believe it's shorter because it slows the player down when walked on.
