### ISSUE TITLE
Thatch Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#111]
### General Information

**Describe the bug:**

I noticed that the Thatch block will render incorrectly underwater, rending water flowing down it's sides.

**To Reproduce:**

1. Place Thatch underwater
3. Observe

**Expected behavior:**

It should render like a normal block instead.

***

### Environment Versions

**Mystic Mods Versions**

- `MysticalLib: v1.10.0`
- `MysticalWorld: v1.6.12`

**Other Versions:**
- `Forge: v28.1.104`
- `Minecraft: v1.14.4`

***

**Screenshot:**

![2019-12-12_01 36 09](https://user-images.githubusercontent.com/12000593/70692014-190e9880-1c80-11ea-8b51-aa41da5c33e7.png)

**Comment by noobanidus** [comment]
Technically all blocks actually do this. You'll notice it occasionally with vertical water... I'll see what I can do about making it waterloggable to avoid that though.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/oO968Mk.png)
