### ISSUE TITLE
[1.12] Spindle has 65 durability instead of 64

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MysticMods/MysticalWorld#113]
### General Information

**Describe the bug:**
The spindle has 65 uses. After turning a full stack of silk pods into silk string, 1 durability point remains. It shows `0/64 durability` but this is an off-by-one error in vanilla.

**Expected behavior:**
I expected the tool to have exactly 64 uses, thus breaking when processing a clean stack of silk pods. This would make inventory management easier when bulk-crafting.

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.1.1
- MysticalWorld: 1.1.0

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): Enigmatica 2 1.74b

**Comment by Birgliss** [comment]
I don't entirely agree with lowering the spindle's durability by 1, given vanilla is also guilty of this sometimes (a flint and steel has 65 uses).

Even though I don't personally agree, I'm not gonna close the issue. There's merit in a config option for durability, at least. The default will likely remain 65, though.

(If you're having trouble with inventory management for now, consider combining the "spent" spindles in the crafting table to get some free extra durability?)

**Comment by noobanidus** [comment]
People can always use CraftTweaker to change the durability of items. I have no intention from changing it from 64, because then we will get a plethora of people saying "hey this is weird it says 63, shouldn't it be 64?"
