### ISSUE TITLE
Barrows still spawning even when disabled

### ISSUE THREAD

**Issue by MasterEnderman** [MysticMods/MysticalWorld#115]
### General Information

**Describe the bug:**
I'm playing in a voidworld generated with topography and even if I disable barrows they still spawn at the bottom of the world (setting the according config to -1)

**To Reproduce:**
1. disable barrow spawning in mysticalworld.cfg (set `BarrowDistance` to `-1`)
2. create a void world with the topography mod
3. barrows spawn above the void

**Expected behavior:**
barrows don't spawn when they are disabled
***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.4.0
- MysticalWorld: 1.6.1
- Roots: 3.0.21

**Other Versions:**
- Other mods you think could cause issues: Topography: 1.10.1
- Forge: 14.23.5.2847
- Minecraft: 1.12.2

***

### Additional Information
**Screenshots (if available):**
![2020-01-05_17 58 26](https://user-images.githubusercontent.com/24524662/71783292-08ceac80-2fe5-11ea-8795-8342e63b6815.png)

**Comment by noobanidus** [comment]
I'm not sure what mod these structures are from, but these aren't Mystical World barrows. Mystical World barrows are *considerably* larger but only spawn on grass surfaces. I'd recommend checking out what other mods that do world generation which you might have installed... sorry I can't be of more help!
