### ISSUE TITLE
Missing Item Tags

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#117]
### General Information

**Describe the bug:**
 
Fences, logs, planks, slabs, stairs, and walls have block tags, but are missing item tags. This mean that these blocks are not compatible with any mods that use these tags in their recipes.

**To Reproduce:**

1. Check data tags in the Minecraft folder
2. Then observe that there are no tags for items.

**Expected behavior:**
 Blocks should have Minecraft tags for their corresponding items.

***

### Environment Versions
 

**Mystic Mods Versions**

- `Mystical Lib v1.10.0`
- `Mystical World v1.6.12`

**Other Versions:**
- `Minecraft v1.14.4`
- `Forge v28.1.111`

***

**Comment by noobanidus** [comment]
You're right... for some reason they're being exported to the mysticalworld tags but aren't... being merged into the Forge tags like they're supposed to.

**Comment by noobanidus** [comment]
OH! They're Minecraft tags, not Forg.e

**Comment by WenXin20** [comment]
Yep. Minecraft also uses the tag `minecraft:oak_logs`, so if wood, stripped wood, or stripped log variants of charred logs are ever added, the tag for those would be `mysticalworld:charred_logs`.

**Comment by noobanidus** [comment]
Yeah, it was my mistake -- I was copying the block tags over but into an internal reference tag rather than a Minecraft tag.
