### ISSUE TITLE
[1.14] Bowled Foods do not return a bowl upon consumption.

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#121]
### General Information

**Describe the bug:**
hrngrhn cronch sawdust

**To Reproduce:**

1. put eggplant in bowl
2. eat eggplant
3. eat bowl 

**Expected behavior:**
The empty bowl should be returned to the player's inventory after eating the food.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.14.4-1.13.0
- MysticalWorld: 1.14.4-1.7.2

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 28.1.116
- Minecraft: 1.14.4
- Modpack (if available): Neo-Devcraft 

***

### Additional Information
**Additional context (optional):**
I've only tested this with the Eggplant Salad and Aubergine Stew. However, it's possible this issue may also occur with the other bowled foods; perhaps even the bottled foods (i.e. cordials) are affected as well.

**Comment by noobanidus** [comment]
This is fixed locally through MysticalWorld, ta.
