### ISSUE TITLE
World Crash upon loading new chunks.

### ISSUE THREAD

**Issue by IAMNameless9t9** [MysticMods/MysticalWorld#122]
**Describe The Bug**
When loading new chunks, whether in an existing world or a starting a new one causes the game to crash.

**To Reproduce:**
Either, 1) load a new world and the crash will occur (with the current version)
Or, 1) go onto a world created before the current version
      2) make sure the new version is installed
      3) Fly out and attempt to load new chunks (may require loading multiple chunks before the 
      crash will occur.) Note: Logging back into a world that crashed this way automatically crashes. 

**Expected behavior:**
The world should not crash upon loading new chunks.

### Environment Versions
The version of Mystical World used: 1.12.2-1.7.1

**Mystic Mods Versions**
- MysticalLib: 1.12.2-1.6.0
- Roots: 1.12.2-3.0.24
- Embers: 1.13 hotfix2

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack: Custom Modpack

**Crash Report:**
https://paste.dimdev.org/asowiruduk.mccrash. 

**Additional context:**
The only solution I have found is to remove mystical world, mysticalLib, and roots then the world loads fine just with all the mod contents missing.

**Comment by noobanidus** [comment]
I'd check your ore generation settings; it would appear that your max Y is lower than your min Y for one configuraiton.

**Comment by IAMNameless9t9** [comment]
You, sir, are a lifesaver, now I just gotta go dig through backups and find the last uncorrupted save! Thanks a ton!
