### ISSUE TITLE
Undead mobs always show hurt animation when attacking players

### ISSUE THREAD

**Issue by lordbowser** [MysticMods/MysticalWorld#123]
When any undead mob attacks a player, they display the hurt animation as if the player was wearing silver/Thorns armor, even if the player's inventory is completely empty. They don't actually take damage (proven with /data get), but the animation still occurs.

Simply find or spawn any undead mob (zombie, skeleton, etc.) and let it attack you; you'll see it play the hurt animation and its hurt sound, but not actually lose health.

No other mods I have installed interfere with mob or weapon/armor mechanics.

Forge version: 28.1.116
Mod version: 1.14.4-1.7.1
Library version: 1.14.4-1.13.0
Patchouli version: Not sure (displays as 1.1-23 ingame, but the .jar is named 1.1-24)

**Comment by noobanidus** [comment]
Ahah! I believe I know the cause of this. I think I'm damaging them and assuming that, as the damage will be 0, nothing will happen; instead I need to check for 0 and *not* call the damage.
