### ISSUE TITLE
Incorrect Aubergine Tags

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#124]
### General Information

**Describe the bug:**

- Aubergines have incorrect item tags, which means compat with Simple Farming & other mods won't work.
- The tags should be `#forge:vegetables`, `#forge:vegetables/eggplant`, `#forge:vegetables/aubergine`, `#forge:crops`, `#forge:crops/eggplant`, & `#forge:crops/aubergine`.

**To Reproduce:**

1. Check Aubergine Tags
2. Check Eggplant Tags from Simple Farming

**Expected behavior:**

- Aubergines should have the correct tag for compat with other mods.

***

### Environment Versions

**Mystic Mods Versions**

- `MysticalLib: v1.13.0`
- `MysticalWorld: v1.7.1`

**Other Versions:**
- `Simple Farming: v1.2.7`
- `Forge: v28.2.0`
- `Minecraft: v1.14.4`

***

**Comment by noobanidus** [comment]
Something must've changed in a recent version of Simple Farming then, because I'm pretty sure I copied the tags from there directly. I'll tweak accordingly.

**Comment by noobanidus** [comment]
What even is the standard? I'm concerned we're going to just add more and more tags because people are inventing their own...

**Comment by WenXin20** [comment]
I believe it's `#forge:vegetables/type`, same for fruit, at least from what I've seen. Similar to how gems and ingots are done.

**Comment by noobanidus** [comment]
Actually, I would disagree, it seems to be `#forge:crops/type`, not vegetables.

**Comment by WenXin20** [comment]
That's what I had found listed for Simple Farming, it uses both.
It uses vegetables to separate it from fruits.

**Comment by noobanidus** [comment]
I've been using `forge:crops/XYZ` for the Registrate rewrite of Mystical World.
