### ISSUE TITLE
Game Launch Error w/ Patchouli Update

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#125]
### General Information

**Describe the bug:**

- After updating Patchouli, I get the following error on game load:
[Log](https://gist.github.com/WenXin20/eb74b3ec91c2935ef3ea88c77523b151)

**To Reproduce:**

1. Install Patchouli
2. Launch game

**Expected behavior:**

- It should work properly with the new update.

***

### Environment Versions

**Mystic Mods Versions**

- `MysticalLib: v1.13.0`
- `MysticalWorld: v1.7.1`

**Other Versions:**
- `Patchouli: v1.1-25`
- `Forge: v28.2.0`
- `Minecraft: v1.14.4`

***

**Comment by noobanidus** [comment]
It's known. I recommend downgrading Patchouli for now until I can get a release out -- and I don't know how long that will take me.

**Comment by noobanidus** [comment]
Okay, fixed sooner rather than later, waiting on approval.

Other issues may happen.
