### ISSUE TITLE
Wet Mud Block selection box is too small

### ISSUE THREAD

**Issue by Mrthomas20121** [MysticMods/MysticalWorld#128]
### General Information

**Describe the bug:**
the wet mud block in the 1.12 version selection box is too small. 
same bug happened to the 1.14 version, surprised nobody noticed in 1.12 https://github.com/MysticMods/MysticalWorld/issues/92

**To Reproduce:**
just place a wet mud block and see its selection box when looking at it.

**Expected behavior:**
i expected the wet mud block selection box to be the full block and just a large part of it.

***

### Environment Versions
1.12.2

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.7.1
- Mystical World: 1.12.2-1.6.0

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): 

***

### Additional Information
**Screenshots (if available):**
https://cdn.discordapp.com/attachments/596485879028252673/675701047955554334/2020-02-08_14.53.11.png

**Additional context (optional):**

**Comment by noobanidus** [comment]
Thanks, looks like when converted to the generated blockstates system I somehow misplaced the wet mud block model -- so while the bounding box was correct, the actual block model wasn't shorter (as it was intended to be).
