### ISSUE TITLE
Cooked apples offer no real benefit as food over uncooked apples

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#130]
### General Information

**Describe the bug:**
If you look at the food and saturation values provided by both the vanilla apple and the cooked apple from Mystical World, they appear to provide the same value.... one would think that cooking it should make it better somehow. Or at least I would.

**To Reproduce:**
1. Get apple
2. Cook apple
3. Stop and wonder why you just bothered to cook it at all

**Expected behavior:**
After going through the trouble to roast my apples, I'd hope they're tastier/somehow provide better food...

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.1.1
- Mystical World: 1.7.1

**Other Versions:**
- Conflicting mod (if regarding mod integration): N/A
- Other mods you think could cause issues: N/A
- Forge: 14.23.5.2847
- Minecraft: 1.12.2

***

### Additional Information
**Screenshots (if available):**

Comparing the hunger/saturation values in JEI with AppleSkin's tooltip info, they look pretty much the same time:

![image](https://user-images.githubusercontent.com/13922447/75105477-85830d80-55c8-11ea-88c2-119d7f4a435a.png)
![image](https://user-images.githubusercontent.com/13922447/75105482-96338380-55c8-11ea-9d4c-f34d61dc1aca.png)

**Comment by noobanidus** [comment]
Solution! Delete cooked apples because dumb idea is dumb.
