### ISSUE TITLE
Frog slime ball drop rate not able to be disabled (set to -1)

### ISSUE THREAD

**Issue by EnderMelody** [MysticMods/MysticalWorld#131]
### General Information

**Describe the bug:**
attempting to disable slime balls dropping from frogs by setting "slimeTime=-1" as recommended by the config crashes the game when loading.

**To Reproduce:**
1. change "slimeTime" in frog config to -1 (or 0)
2. launch
3. game give exception: java.lang.IllegalArgumentException: bound must be positive ....
at epicsquid.mysticalworld.entity.EntityFrog.<init>(EntityFrog.java:39)

change "slimeTime" to positive fixes crash

**Expected behavior:**
disabled slime balls dropping from frogs

***

### Environment Versions
mysticalworld-1.12.2-1.7.1.jar

**Mystic Mods Versions**
mysticalworld-1.12.2-1.7.1.jar
- mysticallib-1.12.2-1.6.0.jar 
- Patchouli-1.0-20.jar

**Other Versions:**
- Forge: forge-14.23.5.2847
- Minecraft: 1.12.2

**Crash Report (if available):**
https://gist.github.com/EnderMelody/b889df1be59aa8abab273de736707bcc

### Additional Information
changing "slimeTime" in frog config to positive fixes crash

**Comment by noobanidus** [comment]
Whoops! Thanks for reporting this. I'll include it in the next release.
