### ISSUE TITLE
Crash during worldgen

### ISSUE THREAD

**Issue by acemagex** [MysticMods/MysticalWorld#132]
### General Information

**Describe the bug:**
World crashed during worldgen, crash report attached.

***

### Environment Versions
jre-x64 1.8.0_51

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.6.0
- MysticalWorld: 1.12.2-1.7.1

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2

***

### Logging Information

**Crash Report (if available):**
// This doesn't make any sense!

Time: 2020-03-10 19:16:14 MST
Description: Exception ticking world

java.lang.NullPointerException
    at net.minecraft.world.gen.feature.WorldGenerator.setBlockAndNotifyAdequately(WorldGenerator.java:37)
    at epicsquid.mysticalworld.world.tree.WorldGenBurntTree.crosSection(WorldGenBurntTree.java:98)
    at epicsquid.mysticalworld.world.tree.WorldGenBurntTree.generateLeafNode(WorldGenBurntTree.java:140)
    at epicsquid.mysticalworld.world.tree.WorldGenBurntTree.generateLeaves(WorldGenBurntTree.java:196)
    at epicsquid.mysticalworld.world.tree.WorldGenBurntTree.generate(WorldGenBurntTree.java:271)
    at epicsquid.mysticalworld.world.WorldGeneratorTrees.generate(WorldGeneratorTrees.java:58)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:990)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: temp
  All players: 1 total; [EntityPlayerMP['Acemagex'/79, l='temp', x=-356.31, y=48.00, z=8160.30]]
  Chunk stats: ServerChunkCache: 1625 Drop: 0
  Level seed: -8916030749094278191
  Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-45,64,165), Chunk: (at 3,4,5 in -3,10; contains blocks -48,0,160 to -33,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 35440 game time, 35440 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 66008 (now: false), thunder time: 26093 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1458800440 bytes (1391 MB) / 4828692480 bytes (4605 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
  IntCache: cache: 1, tcache: 43, allocated: 16, tallocated: 154
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 165 mods loaded, 165 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                        | Version                  | Source                                             | Signature                                |
       |:------ |:------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                 | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                       | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge                     | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | agriseasons               | 1.0.2                    | minecraft.jar                                      | 075143b8d04af6213d5b5936048e9b8012eb5cec |
       | LCHIJA | creativecoredummy         | 1.0.0                    | minecraft.jar                                      | None                                     |
       | LCHIJA | openmodscore              | 0.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore               | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCHIJA | albedocore                | 0.1                      | minecraft.jar                                      | None                                     |
       | LCHIJA | randompatches             | 1.12.2-1.21.0.0          | randompatches-1.12.2-1.21.0.0.jar                  | None                                     |
       | LCHIJA | infinitylib               | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                             | None                                     |
       | LCHIJA | agricraft                 | 2.12.0-1.12.0-a6         | AgriCraft-2.12.0-1.12.0-a6.jar                     | None                                     |
       | LCHIJA | aiimprovements            | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
       | LCHIJA | akashictome               | 1.2-12                   | AkashicTome-1.2-12.jar                             | None                                     |
       | LCHIJA | albedotorches             | 1.1.2                    | AlbedoTorches-1.1.2.jar                            | None                                     |
       | LCHIJA | albedo                    | 1.0.0                    | albedo-1.12.2-1.1.0.jar                            | None                                     |
       | LCHIJA | biomesoplenty             | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
       | LCHIJA | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                  | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
       | LCHIJA | craftstudioapi            | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | harvestcraft              | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zf.jar                    | None                                     |
       | LCHIJA | ctm                       | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
       | LCHIJA | twilightforest            | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | animania                  | 1.7.3                    | animania-1.12.2-1.7.3.jar                          | None                                     |
       | LCHIJA | antiqueatlas              | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | antiqueatlasoverlay       | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | LCHIJA | applecore                 | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCHIJA | crafttweaker              | 4.1.20                   | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | mtlib                     | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
       | LCHIJA | modtweaker                | 4.0.18                   | modtweaker-4.0.18.jar                              | None                                     |
       | LCHIJA | jei                       | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                          | None                                     |
       | LCHIJA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCHIJA | athenaeum                 | 1.12.2-1.17.4            | athenaeum-1.12.2-1.17.4.jar                        | None                                     |
       | LCHIJA | mousetweaks               | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHIJA | artisanworktables         | 1.12.2-1.22.15           | artisanworktables-1.12.2-1.22.15.jar               | None                                     |
       | LCHIJA | patchouli                 | 1.0-20                   | Patchouli-1.0-20.jar                               | None                                     |
       | LCHIJA | artisanintegrations       | 1.12.2-1.2.0             | artisanintegrations-1.12.2-1.2.0.jar               | None                                     |
       | LCHIJA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | astralsorcery             | 1.10.22                  | astralsorcery-1.12.2-1.10.22.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | attributefix              | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | quark                     | r1.6-178                 | Quark-r1.6-178.jar                                 | None                                     |
       | LCHIJA | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar        | None                                     |
       | LCHIJA | base                      | 3.13.0                   | base-1.12.2-3.13.0.jar                             | None                                     |
       | LCHIJA | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | bhc                       | 2.0.3                    | baubley-heart-canisters-1.12.2-2.0.3.jar           | None                                     |
       | LCHIJA | bedbugs                   | @VERSION@                | BedBugs-1.12-1.0.1.jar                             | None                                     |
       | LCHIJA | forgelin                  | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | betterfoliage             | 2.3.1                    | BetterFoliage-MC1.12-2.3.1.jar                     | None                                     |
       | LCHIJA | betterquesting            | 3.5.323                  | BetterQuesting-3.5.323.jar                         | None                                     |
       | LCHIJA | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | forestry                  | 5.8.2.418                | forestry_1.12.2-5.8.2.418.jar                      | None                                     |
       | LCHIJA | binniecore                | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | binniedesign              | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | genetics                  | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | botany                    | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | extrabees                 | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | extratrees                | 2.5.1.200                | binnie-mods-1.12.2-2.5.1.200.jar                   | None                                     |
       | LCHIJA | blockcraftery             | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                     | None                                     |
       | LCHIJA | blockdrops                | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                        | None                                     |
       | LCHIJA | blur                      | 1.0.4-14                 | Blur-1.0.4-14.jar                                  | None                                     |
       | LCHIJA | bmtr                      | 0.4                      | BringMeTheRings-0.4.jar                            | None                                     |
       | LCHIJA | buildinggadgets           | 2.8.1                    | BuildingGadgets-2.8.1.jar                          | None                                     |
       | LCHIJA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | roots                     | 1.12.2-3.0.25            | Roots-1.12.2-3.0.25.jar                            | None                                     |
       | LCHIJA | mysticalworld             | 1.12.2-1.7.1             | mysticalworld-1.12.2-1.7.1.jar                     | None                                     |
       | LCHIJA | chisel                    | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
       | LCHIJA | chiselsandbits            | 14.33                    | chiselsandbits-14.33.jar                           | None                                     |
       | LCHIJA | chunkpregenerator         | 2.1                      | Chunk Pregenerator V1.12-2.2.jar                   | None                                     |
       | LCHIJA | chunkanimator             | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                       | None                                     |
       | LCHIJA | clumps                    | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJA | codechickenlib            | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhworld                 | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | LCHIJA | comforts                  | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | cyclopscore               | 1.6.1                    | CyclopsCore-1.12.2-1.6.1.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | commoncapabilities        | 2.4.5                    | CommonCapabilities-1.12.2-2.4.5.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | contenttweaker            | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                    | None                                     |
       | LCHIJA | controlling               | 3.0.8                    | Controlling-3.0.8.jar                              | None                                     |
       | LCHIJA | cookingforblockheads      | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
       | LCHIJA | craftingtweaks            | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | LCHIJA | ctgui                     | 1.0.0                    | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCHIJA | opframe                   | 1.4.0                    | OnlinePicFrame_v1.4.35_mc1.12.2.jar                | None                                     |
       | LCHIJA | creativecore              | 1.10.0                   | CreativeCore_v1.10.2_mc1.12.2.jar                  | None                                     |
       | LCHIJA | customloadingscreen       | 1.12.2-1.4.1             | CustomLoadingScreen-1.12.2-1.4.1.jar               | None                                     |
       | LCHIJA | custommainmenu            | 2.0.9.1                  | CustomMainMenu-MC1.12.2-2.0.9.1.jar                | None                                     |
       | LCHIJA | defaultoptions            | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                    | None                                     |
       | LCHIJA | ding                      | 1.0.2                    | Ding-1.12.2-1.0.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | sereneseasons             | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
       | LCHIJA | orelib                    | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                 | 3.6.0.2                  | DynamicSurroundings-1.12.2-3.6.0.2.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | embers                    | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                   | None                                     |
       | LCHIJA | enchdesc                  | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enderstorage              | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | extrabitmanipulation      | 1.12.2-3.4.1             | ExtraBitManipulation-1.12.2-3.4.1.jar              | None                                     |
       | LCHIJA | fairylights               | 2.1.10                   | fairylights-2.1.10-1.12.2.jar                      | None                                     |
       | LCHIJA | fbp                       | 2.4.1                    | FancyBlockParticles-1.12.x-2.4.1.jar               | None                                     |
       | LCHIJA | farseek                   | 2.5                      | Farseek-1.12-2.5.jar                               | None                                     |
       | LCHIJA | fastfurnace               | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCHIJA | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | LCHIJA | fastbench                 | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                     | None                                     |
       | LCHIJA | foamfix                   | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | forgemultipartcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCHIJA | minecraftmultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCHIJA | fpsreducer                | mc1.12.2-1.14.1          | FpsReducer-mc1.12.2-1.14.1.jar                     | None                                     |
       | LCHIJA | ftbbackups                | 1.1.0.1                  | FTBBackups-1.1.0.1.jar                             | None                                     |
       | LCHIJA | ftblib                    | 5.4.7.0                  | FTBLib-5.4.7.0.jar                                 | None                                     |
       | LCHIJA | ftbutilities              | 5.4.0.124                | FTBUtilities-5.4.0.124.jar                         | None                                     |
       | LCHIJA | globalgamerules           | 2.2                      | GlobalGameRules-1.12.2-2.2.7.jar                   | None                                     |
       | LCHIJA | grapplemod                | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                        | None                                     |
       | LCHIJA | gravestone                | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
       | LCHIJA | wasaila                   | 1.0                      | Wasaila-1.0.jar                                    | None                                     |
       | LCHIJA | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | initialinventory          | 2.0.2                    | InitialInventory-3.0.0.jar                         | None                                     |
       | LCHIJA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | jeibees                   | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
       | LCHIJA | jeiintegration            | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                 | None                                     |
       | LCHIJA | jehc                      | 1.7.0                    | just-enough-harvestcraft-1.12.2-1.7.0.jar          | None                                     |
       | LCHIJA | loottweaker               | 0.1.5                    | LootTweaker-0.1.5+MC1.12.2.jar                     | None                                     |
       | LCHIJA | jeresources               | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | laggoggles                | FAT-1.12.2-4.9           | LagGoggles-FAT-1.12.2-4.9.jar                      | None                                     |
       | LCHIJA | loyaltyrewards            | 0.3.2                    | Loyalty-Rewards-0.3.2.jar                          | None                                     |
       | LCHIJA | malisiscore               | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LCHIJA | malisisdoors              | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | LCHIJA | mcwbridges                | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                     | None                                     |
       | LCHIJA | metallurgy                | 0.3.3                    | Metallurgy-4-Reforged-0.3.3.jar                    | None                                     |
       | LCHIJA | mtrm                      | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
       | LCHIJA | testdummy                 | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                         | None                                     |
       | LCHIJA | mobends                   | 0.24                     | mobends-0.24_for_MC-1.12.jar                       | None                                     |
       | LCHIJA | moreoverlays              | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
       | LCHIJA | llibrary                  | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs               | 1.5.4                    | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHIJA | multimine                 | 1.6.2                    | MultiMine-1.12.2.jar                               | None                                     |
       | LCHIJA | norecipebook              | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
       | LCHIJA | openmods                  | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | placebo                   | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LCHIJA | potioncore                | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                      | None                                     |
       | LCHIJA | potionfingers             | r1.0-8                   | PotionFingers-r1.0-8.jar                           | None                                     |
       | LCHIJA | psi                       | r1.1-77                  | Psi-r1.1-77.jar                                    | None                                     |
       | LCHIJA | qualitytools              | 1.0.7_for_1.12.2         | QualityTools-1.0.7_for_1.12.2.jar                  | None                                     |
       | LCHIJA | roughmobsrevamped         | 2.3.13                   | roughmobsrevamped-1.12.2-2.3.13.jar                | None                                     |
       | LCHIJA | spiceoflife               | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
       | LCHIJA | bq_standard               | 3.4.173                  | StandardExpansion-3.4.173.jar                      | None                                     |
       | LCHIJA | stg                       | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCHIJA | storagedrawers            | 1.12.2-5.4.1             | StorageDrawers-1.12.2-5.4.1.jar                    | None                                     |
       | LCHIJA | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar                | None                                     |
       | LCHIJA | streams                   | 0.4.8                    | Streams-1.12-0.4.8.jar                             | None                                     |
       | LCHIJA | surge                     | 2.0.77                   | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tipthescales              | 1.0.4                    | TipTheScales-1.12.2-1.0.4.jar                      | None                                     |
       | LCHIJA | toastcontrol              | 1.8.1                    | Toast Control-1.12.2-1.8.1.jar                     | None                                     |
       | LCHIJA | translocators             | 2.5.2.81                 | Translocators-1.12.2-2.5.2.81-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | undergroundbiomes         | 1.3.7                    | UndergroundBiomesConstructs-1.12-1.3.7.jar         | None                                     |
       | LCHIJA | vanillafix                | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | vtb                       | 2.0.0                    | VillagerTradingBan-2.0.0.6-universal.jar           | None                                     |
       | LCHIJA | wailaharvestability       | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
       | LCHIJA | wawla                     | 2.6.274                  | Wawla-1.12.2-2.6.274.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | worleycaves               | 1.5.1                    | worleycaves-1.5.1.jar                              | None                                     |
       | LCHIJA | phosphor-lighting         | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | reauth                    | 3.6.0                    | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | solcarrot                 | 1.8.3                    | solcarrot-1.12.2-1.8.3.jar                         | None                                     |
       | LCHIJA | hungeroverhaul            | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar         | None                                     |
       | LCHIJA | mysticallib               | 1.12.2-1.6.0             | mysticallib-1.12.2-1.6.0.jar                       | None                                     |
  Loaded coremods (and transformers): AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      FMLPlugin (albedo-1.12.2-1.1.0.jar)
                                        elucent.albedo.asm.ASMTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.22.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      agriseasons (agriseasons-1.12.2-1.0.2.jar)
                                        xyz.dogboy.agriseasons.AgriSeasonsTransformer
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.4.1.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      FarseekCoreMod (Farseek-1.12-2.5.jar)
                                        farseek.core.FarseekClassTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.2_mc1.12.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  [Psi] Active spell: None
  Suspected Mods: Mystical World (mysticalworld)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Acemagex'/79, l='temp', x=-356.31, y=48.00, z=8160.30]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

***

### Additional Information

**Additional context:**
Digging through ocean floor, blocked off water ~4 blocks below water, crashed immediately. Not sure if correlated.

**Comment by noobanidus** [comment]
Unfortunately I think this is one of those intermittent issues that I'm never going to be able to track down. I've managed to get copies of the erroring worlds but the issue doesn't seem to recur. The crash itself is crazy because it implies that somehow the Vanilla tree generation has become corrupted -- as the line immediately before checks to make sure it isn't null before calling another function which then finds that non-null value IS null.

I think it may be a cross-mod interaction but I'm not sure.
