### ISSUE TITLE
Missing Pelt to Leather Recipe?

### ISSUE THREAD

**Issue by sealchan1** [MysticMods/MysticalWorld#133]
Mystical World Description page indicates...

When [a fox is] slain, they will drop pelts () which can be combined together to make leather.

...but JEI indicates no such recipe and manual efforts on my part have failed to guess it.

Minecraft 1.12.2
Mystical World v1.12.2-1.7.1
Mystical Lib 1.1.1
Roots 1.12.2-3.0.25

**Comment by noobanidus** [comment]
I'm not sure what happened to that, that's weird.

**Comment by sealchan1** [comment]
I was going to walk a fine line between keeping some Foxes as pets and slaughtering some for the pelts...I'm glad I checked the recipe first or I might have been really sad about Foxy and his parents.  :-o

**Comment by noobanidus** [comment]
This is fixed in the most recent release!

**Comment by sealchan1** [comment]
Thanks!
