### ISSUE TITLE
1.12 Deer Config not working

### ISSUE THREAD

**Issue by UwUbird** [MysticMods/MysticalWorld#135]
I attempted to disable the deer several times but they continue to spawn. Config is below.
[mysticalworld.txt](https://github.com/MysticMods/MysticalWorld/files/4357560/mysticalworld.txt)
Edit: The same issue applies to foxes as well

**Comment by noobanidus** [comment]
Hm, this might be an issue with the config just not being read then... I'll look into it.

**Comment by UwUbird** [comment]
I found the issue, custom mob spawner was overriding the config and making them spawn. It's working fine now:)

**Comment by noobanidus** [comment]
Oh, I'm glad! There have been instances where config values aren't being read which were hard to sort out. Glad it was so simple.
