### ISSUE TITLE
Option so silkworms not eternal

### ISSUE THREAD

**Issue by toruPuchuu** [MysticMods/MysticalWorld#143]
**Describe your suggestion:**
 Please add an option to end the silkworm's life cycle when they create a cocoon, 

**Describe alternatives you've considered:**
Disable silkworms.

**Additional context:**
I really like silkworms, as they are a nice alternative to hunting for sheep or spiders to get your first bed. But IMO their eternal life creates mid to end game level quantities of string in the early game . So they feel OP in the modpack I'm putting together.

It would be cool if they hatched into butterflies! :)

Thanks

**Comment by noobanidus** [comment]
Yes! This is definitely happening: I'm planning on actually preventing them from being an entity and making them a block -- a sort of cocoon that grows and hangs off the underside of some leaves (thanks to a suggestion by Dinar) and drops silk thread and then eventually decays

**Comment by noobanidus** [comment]
I'm going to close this in favor of #107 which is the older topic. I definitely agree that this needs to be happen, and it will happen for both 1.12 and 1.14.

**Comment by noobanidus** [comment]
With the cannibalism option, this might make a come-back.

**Comment by noobanidus** [comment]
Okay, so territorialism is now configurable in 1.12.2, and it's now possible to specify a maximum lifetime in ticks before a silkworm just automatically dies.

**Comment by toruPuchuu** [comment]
Sounds good! And 1.16.4 is in beta - yea
