### ISSUE TITLE
[1.12.2] Crash caused by EnderZoo's Epic Squid

### ISSUE THREAD

**Issue by ReeCodes** [MysticMods/MysticalWorld#146]
### General Information

**Describe the bug:**
A client-crash caused by EnderZoo's Epic Squid

**To Reproduce:**
1. Put EnderZoo and MW into the same mod folder, I guess...

**Expected behavior:**
No crashing.

***

### Environment Versions
mysticalworld-1.12.2-1.8.2
EnderIO-zoo-1.12.2-5.0.44

**Mystic Mods Versions**

- MysticalLib: 1.2.1

**Other Versions:**
- Conflicting mod (if regarding mod integration): EnderZoo
- Other mods you think could cause issues: /
- Forge: forge-14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
https://pastebin.com/S1D36hp3

**Latest Log (if necessary):**
https://pastebin.com/g4u2taf2

**Comment by noobanidus** [comment]
Please update your MysticalLib, You are a considerable number of versions out of date, [1.7.0](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/all) is the latest. 1.2.1 is from ... May of last year.
