### ISSUE TITLE
How to modify spawn rates

### ISSUE THREAD

**Issue by MunLau24** [MysticMods/MysticalWorld#147]
Hello! 

I need a bit of help. 
I want to modify the spawn rates on the mod, so the mobs spawn at a higher rate. 

My question, do I have to put the number higher or lower. Because in some mods spawn rates you have to lower the value. 
Example, for deers: spawn rate is set at 6. If I put it at 30, it increases the chances of spawn??

Thanks!!

**Comment by noobanidus** [comment]
Hi there!

Generally speaking, when it comes to weights in Vanilla, higher = more frequently. This applies also to Mystical World creatures: putting a higher number should make them appear more frequently.

Other systems that use the reverse are probably not using the Vanilla spawn system.

**Comment by MunLau24** [comment]
oh thanks awesome!!!! 

That's what I thougt but wanted to be sure. 

also, do you think that mods like thaumcraft, bewitchment or zoocraft could interfere with the spawn? Yesterday I was exploring a bit and found like one frog one deer and one sprout xd.

**Comment by noobanidus** [comment]
The issue here is that, when lots of mods add more and more creatures, there are more creatures to choose from, so you will end up with an artificial increase in rarity. There is not too much that you can do about it unless Bewitchment/Zoocraft have options for adjusting their spawn rates.
