### ISSUE TITLE
Eating from stacked Aubergine Salads replaces entire ItemStack with an empty bowl 

### ISSUE THREAD

**Issue by simibubi** [MysticMods/MysticalWorld#149]
Sorry for the sparse information, I think this should suffice for repro/hotfix.
Cheers!

Mod version: mysticalworld-1.14.4-1.9.0
Modpack: OpenDevCraft

**Comment by noobanidus** [comment]
Thank you! Yes, I literally delete the note I made because I swore I fixed it but apparently never did. :(
