### ISSUE TITLE
Fairies

### ISSUE THREAD

**Issue by DemonfangArun** [MysticMods/MysticalWorld#162]
I loved these little things back when they were in the Roots mod, and they were lost in the 3.0 update. Could we get them back? Would also be nice to have some sort of block that could be configured to spawn them (or any other mob from this mod).

Example spawner UI:

Mob: __________
Spawn rate: Every __________ seconds
Max in ______ blocks radius: ________

**Comment by noobanidus** [comment]
They are actually partially implemented in Roots 3.0 but as they're linked to the grove system (fairies spawn when you have a Fairy Grove set up with enough interesting things to cause them to spawn). They'll most likely appear once 3.1 is released and the 3.2 port to 1.15.2 begins.

**Comment by noobanidus** [comment]
(For the record, I don't tend to add it into any 1.12 mod as it requires a fair amount of work. I'd recommend checking out EmberRootsZoo (I believe it's called) by Lothrazar if you want fairies.)

**Comment by DemonfangArun** [comment]
Ah ok thanks for the information. I'll just wait until 1.15, the small decorative thing I wanted to do doesn't warrant the effort.
