### ISSUE TITLE
Stuffed Aubergine recipe takes Raw Aubergine instead of Cooked Aubergine

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#165]
### General Information
In earlier versions of Mystical World, Stuffed Aubergine required you to use cooked aubergine.
In more recent versions this has regressed to using raw aubergine instead, which is likely a mistake instead of intentional due to the textures of both stuffed aubergine and cooked aubergine being cut in halves.
### Environment Versions

**Mystic Mods Versions**
The testing versions as provided in `#testing-admin`, uploaded 4/20/2020

**Comment by noobanidus** [comment]
Should be fixed for the next release.
