### ISSUE TITLE
Crash (MysticalWorld - MC Eternal 1.3.5.3)

### ISSUE THREAD

**Issue by ariosos** [MysticMods/MysticalWorld#168]
Was exploring the world (using a slime sling to move quickly), then entered a small mossy cobble structure. First block in, the game crashed. (not sure if the structure is even related). Crash screen also mentions Tinkers Alloying Addon. Not sure why that would conflict, too - maybe overlapping structures? Seems to be trying to generate a burnt tree.

Crash Report - https://pastebin.com/3DBHf6Uy

![image](https://user-images.githubusercontent.com/7917753/82162383-06713e80-9872-11ea-9361-812c37f6b8f3.png)

**Comment by noobanidus** [comment]
You might need to ask MC Eternal to update the version of Mystical World, as I'm pretty sure this was fixed fully in the most recent release.
