### ISSUE TITLE
Mystical huts + structure interactions

### ISSUE THREAD

**Issue by Degsdegsdegs** [MysticMods/MysticalWorld#17]
Per nooby's request: [Witch huts/mystic huts have weird interactions with other structures.  ](https://i.imgur.com/YvYblTr.png) This is a charm village and a waystone, as an FYI.

**Comment by duely** [comment]
I feel like the chunk should be tested for the presence of a structure and be discarded if one exists; hopefully that will resolve any issue? I'm not entirely certain but it might help.

**Comment by duely** [comment]
I'm hopeful that recent changes will improve this.
