### ISSUE TITLE
Dying with a shouldered beetle produces no grave

### ISSUE THREAD

**Issue by NillerMedDild** [MysticMods/MysticalWorld#170]
### General Information

**Describe the bug:**
Dying with a shouldered beetle produces no grave, from Corail's Tombstone mod.

**To Reproduce:**

1. Tame Beetle
2. Right-click Beetle onto shoulders
3. Put any item in your inventory (so a grave would normally spawn)
4. Die
5. Observe a lack of grave

**Expected behavior:**
I expected a gravestone to appear.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: mysticallib-1.14.4-1.16.1
- MysticalWorld: mysticalworld-1.14.4-1.9.3

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Corail's Tombstone: tombstone-4.3.6-1.14.4
- Forge: 1.14.4-28.2.16
- Minecraft: 1.14.4
- Modpack Enigmatica 4

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Latest Log (if necessary):**

https://gist.github.com/NillerMedDild/91399307cc8a05a6c2b8b4e445f08594

**Comment by noobanidus** [comment]
That's really strange, it shouldn't be cancelling any events and it should just cascade downwards... I'll look into it further.

**Comment by noobanidus** [comment]
This'll be fixed in the next release (and the 1.15.2 release... which doesn't have shouldered animals yet).
