### ISSUE TITLE
Crash on Tame (For Foxes)

### ISSUE THREAD

**Issue by AmidaSama** [MysticMods/MysticalWorld#174]
So we have this mod in our modpack, and when you try to tame the foxes with the apple it instantly crashes the server.

**Comment by noobanidus** [comment]
Which version of Mystical World is this in? Could you please provide a copy of the crash report?

**Comment by AmidaSama** [comment]
Yeah, 
[crash-2020-07-18_20.35.28-server (1).txt](https://github.com/MysticMods/MysticalWorld/files/4945123/crash-2020-07-18_20.35.28-server.1.txt) I believe this is the crash file for it from the server. We are running the most recent version of Valhelsia 2 version 2.2.5.

**Comment by noobanidus** [comment]
That was rather frustrating. It turns out that code got converted to client-only... I think I've fixed it, and made a new release.
