### ISSUE TITLE
World generation stuck at 0% if Mystical world ore generation is disabled

### ISSUE THREAD

**Issue by 3x1at1on** [MysticMods/MysticalWorld#176]
### General Information

**Describe the bug:**
World generation gets stuck at 0% when ore generation in config is disabled using 0 values as explained in the config file.
Also worth mentioning that Mystical World Ores do not generate in custom dimensions like https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension

**To Reproduce:**
1. Install Mystical world
2. Disable ore generation
3. Create new world
4. Stuck at 0%

**Expected behavior:**
Worlds would generate normally with Ore Generation disabled.
World definitely generates normally with Ore Generation enabled.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 2.0.1
- Mystical World 2.0.3

**Other Versions:**
- Forge: 31.2.31
- Minecraft: 1.15.2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
Config file settings https://pastebin.com/t19LruQP

**Crash Report (if available):**
No crash report

**Latest Log (if necessary):**
I could not find a relevant section in the log but can provide a full log if felt required.

***

**Comment by noobanidus** [comment]
Ah, bugger. I'll have to adjust the generator to also "do nothing"... or at least look into it further. Sorry, I didn't notice this issue and it's not handled in the most recent update (2.0.4) that I've released.

I also need to update the configuration file to allow you to specify dimensions specifically. I believe that was added specifically so that our ores wouldn't spawn in other dimensions, but I think my solution (overworld only) was way too simplistic.

**Comment by noobanidus** [comment]
Okay, I've resolved the ore failing to spawn if disabled. Now for the dimensions...

**Comment by noobanidus** [comment]
![](https://i.imgur.com/QTsUKIM.png)

It's not perfect and I had to create a new filler-block-type in order to cover all the standard vanilla dimensions, but that should allow you to spawn ore in all vanilla (and other) dimensions. Will include in the next release.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/v333TWr.png)

And working in the nether!
