### ISSUE TITLE
Middle-clicking doesn't give spawn eggs

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#177]
### General Information

**Describe the bug:**
 
- Middle-clicking mobs in creative does not provide any spawn eggs

**To Reproduce:**

1. Spawn in a mob
2. Try middle-clicking to get a spawn egg

**Expected behavior:**
 
- Spawn egg given on middle-click

***

### Environment Versions

**Mystic Mods Versions**

- `Mystical Lib: v2.0.1`
- `Mystical World v2.0.4`

**Other Versions:**
- `Forge: v31.2.31`
- `Minecraft: v1.15.2`

**Comment by noobanidus** [comment]
I actually had no idea this was a vanilla behaviour. I won't lie, it's not a high priority for me to fix right.

**Comment by WenXin20** [comment]
That's fine, just something I noticed since it worked with Druidcraft's mobs.
