### ISSUE TITLE
[1.15.2] Crash when oregen is disabled (feature placement)

### ISSUE THREAD

**Issue by katubug** [MysticMods/MysticalWorld#179]
### General Information

**Describe the bug:**
Upon attempting to create/enter a new singleplayer world, I am receiving a crash linked below.

This was not occurring on my development instance. The main differences there are that my dev instance does not use Optifine/OptiForge, and the last time I attempted creating a new singleplayer world there, I did not have the ores in Mystical World disabled (which I now do). Here is my Mystical World config: https://pastebin.com/LV8bR43g

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 2.0.1.
- Mystical World: 2.0.4

**Other Versions:**
- Conflicting mod (if regarding mod integration): n/a?
- Other mods you think could cause issues: Unsure, potentially Biomes You'll Go?
- Forge: 31.2.31
- Minecraft: 1.15.2
- Modpack (if available): https://www.curseforge.com/minecraft/modpacks/rustic-wanderings/files/3013224

***

### Logging Information

**Crash Report (if available):**
https://pastebin.com/hKX3Eb4x

**Latest Log (if necessary):**
https://paste.ee/p/iAm68

**Comment by katubug** [comment]
Update: removing Optifine and Optiforge did not make a difference.

**Comment by katubug** [comment]
Update: It actually also happened on my multiplayer server, once new chunks were generated with the mod added.

In singleplayer, deleting the config and allowing it to regen worked. Hopefully same on the server. xD

**Comment by 3x1at1on** [comment]
Update to 2.0.5 as it fixes this issue.
Essentially a duplicate of this issue #176

**Comment by katubug** [comment]
Got it, will do! Closing for now.
