### ISSUE TITLE
Foxes hitting through fences

### ISSUE THREAD

**Issue by ChelonianEgghead** [MysticMods/MysticalWorld#180]
### General Information

**Describe the bug:**
Foxes are able to hit through fences, which can be devastating to chicken farms.

**To Reproduce:**
1. Build a pen out of fences
2. Put some chickens in the pen
3. Put a fox outside the pen.

**Expected behavior:**
Foxes should be unable to hit through fences.

***

### Environment Versions
Manjaro Linux
OpenJDK JRE 8

**Mystic Mods Versions**

- MysticalLib: 1.7.0

**Other Versions:**
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

**Comment by noobanidus** [comment]
That's strange, I'll need to investigate what's different about their melee attacks and bounding boxes versus a wild wolf.

**Comment by noobanidus** [comment]
Okay, it's taken a while, but in my testing in Vanilla, it looks like they display the same behaviour as wolves do when encountering a pen of sheep: they will actually attack them through the fence, if the sheep are close enough.

I don't see any way of fixing it, I'm afraid. It seems to be a vanilla issue.
