### ISSUE TITLE
Crash when trying to tame beetle with melon seeds

### ISSUE THREAD

**Issue by orionSquared** [MysticMods/MysticalWorld#181]
So we're running the most recent file of Valhelsia 2, 2.2.5 and when trying to tame a beetle with melon seeds, it crashes the entire server. I have this crash report for you. Please let me know if there's anything I can do to help or test for you.

https://pastebin.com/HhZTQUBa

**Comment by Birgliss** [comment]
I believe this was fixed in Mystical World 1.15.2-2.0.3 during commit fd98b64.
Your version of Valhelsia 2 has 1.15.2-2.0.2.
Can you try updating the mod manually to see if the crash persists?
