### ISSUE TITLE
[1.12.2] UndergroundBiomes crash.

### ISSUE THREAD

**Issue by EnderBro123** [MysticMods/MysticalWorld#182]
### General Information

**Describe the bug:**

Game crashes.

**To Reproduce:**

Use the mod.

**Expected behavior:**

The game starting.

### Environment Versions

MC 1.12.2, Forge 2854, MW 1.12.2-1.8.4.

### Logging Information
https://pastebin.com/Hu0kzmTE

**Latest Log (if necessary):**
[latest.log](https://github.com/MysticMods/MysticalWorld/files/5052103/latest.log)

**Comment by noobanidus** [comment]
Please read the crash report. You've run out of block IDs, something that can happen in versions before 1.13 as the registry is limited to 4096 items. You might need to install a mod like "Just Enough IDs" or something.
