### ISSUE TITLE
[Suggestion] Set Patchouli mod as a requirement mod of MysticalWorld

### ISSUE THREAD

**Issue by RisingInIris2017** [MysticMods/MysticalWorld#185]
**Describe your suggestion:**
When Mystical World Mod 2.0.6 is installed, if the [Patchouli](https://github.com/Vazkii/Patchouli) Mod is not present in the Minecraft instance, the game will crash during the loading process(for example, [this crash report](https://paste.ubuntu.com/p/ZcwRnXYsF8/) ), rather than show "Mystical World mod needs Patchouli Mod to run" with Forge's required mod display screen.
Considering not all players can find out that they *must* install Patchouli Mod to solve the crash problem through reading the crash-report,
I would like to suggest that you might set Patchouli as one of MysticalWorld mod's required mod,
so that when Patchouli mod is not installed, game will display a relatively easy-to-read information by Forge's requirement mod screen.
**Describe alternatives you've considered:**
Set Patchouli Mod as a required mod of Mystical World Mod,
so that when Patchouli mod is not installed, game will display a relatively easy-to-read information by Forge's requirement mod screen.

**Comment by noobanidus** [comment]
Hm, I thought I already had! My apologies. That's definitely something I'd like to have done for the next release.

**Comment by noobanidus** [comment]
This should be done for the next release.
