### ISSUE TITLE
Bugs I found

### ISSUE THREAD

**Issue by Arctic90x** [MysticMods/MysticalWorld#19]
When it comes to disabling anything does nothing.

Not all items are showing up in JEI for what I see it's not showing Copper, Silver and Amethyst Tools, Armor and Weapons, besides the Silver and Amethyst Knives.

**Comment by duely** [comment]
I'm sorry, can you clarify exactly what you are doing, the behaviour that you are experience, and what you expected would happen?

At the minute, disabling copper, silver or amethyst (or all of them) does not disable copper, silver or amethyst tools. 

Disabling dusts, tiny dusts, nuggets, ingots, and blocks should prevent them from being registered and therefore they will not show up in JEI.

**Comment by Arctic90x** [comment]
All I was doing was trying to disable armor, weapons, and tools from Mystical World besides the silver knife how it works well with the Silver items from the "Ice and Fire" mod like we talked about in comments like a week ago.

Besides that, I have the gui crafting hub disabled from another mod so it would be nice to be able to see everything if in JEI but if items are disabled hide them.

Have in the config file itself the ability to turn off individual sets of each material type for "armor, weapons, and tools" but have the knives in individual setting each one having its own disabling option how Roots uses knives. 

To be honest I feel I may be asking for too much if so I am sorry I am just wanting to see the mod be the best it can be a for some people they can get mad over it.

Also, do you have a patron I can help support you?

**Comment by duely** [comment]
Okay, I believe this has been resolved with the conditional recipes predicated on copper being enabled, etc, plus the ability to manually disable.
