### ISSUE TITLE
[1.12.2] Crash everytime I enter the nether

### ISSUE THREAD

**Issue by FerriFinder** [MysticMods/MysticalWorld#190]
### General Information

**Describe the bug:**
Entering the nether crashes the game within about 10 seconds.

**To Reproduce:**

1. Generate new world
2. Create a nether portal
3. Enter the nether and walk a distance away

**Expected behavior:**

***

### Environment Versions
Minecraft 1.12.2

**Mystic Mods Versions**

- MysticalLib: 1.12.2 - 1.7.0
- MysticalWorld: 1.12.2 - 1.8.4

**Other Versions:**
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): none 

***

### Logging Information
<script src="https://gist.github.com/FerriFinder/dc90cb9d8d579d0367b06667b28413ea.js"></script>

**Crash Report (if available):**
<script src="https://gist.github.com/FerriFinder/3c6c189743863c5d2efce4adbe914c10.js"></script>

**Comment by noobanidus** [comment]
Can you provide a copy of the config you have for Mystical World? 

It's possibly my fault for not sanitizing the configuration values, but I presume you've set a negative number (or zero) for spawning lava cats instead of setting the "spawn lava cats" option to false. It's possible that a negative number (or zero) for spawn chance/spawn weight would cause this error.

**Comment by FerriFinder** [comment]
> # Configuration file

general {
    # Minimum distance between Barrow structures. Set to -1 to disable.
    # Min: -1
    # Max: 2147483647
    I:BarrowDistance=400

    # Grant the Patchouli-based Guide Book when first joining the server
    B:GiveBook=false

    # Mininmum distance between Hut structures. Set to -1 to disable.
    # Min: -1
    # Max: 2147483647
    I:HutDistance=400

    # Inject some items from Mystical World into dungeon & other loot chests
    B:InjectLoot=false

    # Maximum nubmer of pulls for injected loot
    I:InjectMaximum=1

    # Minimum number of pulls for injected loot
    I:InjectMinimum=1

    # Enable squid drops
    B:InjectSquid=false

    ##########################################################################################################
    # mobs
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawning of mobs in Mystical World and dependent mods.
    ##########################################################################################################

    mobs {
        # Enable the spawning of Beetle.
        B:spawnBeetle=true

        # Enable the spawning of Deer.
        B:spawnDeer=true

        # Enable the spawning of Endermini.
        B:spawnEndermini=true

        # Enable the spawning of Fox.
        B:spawnFox=true

        # Enable the spawning of Frog.
        B:spawnFrog=true

        # Enable the spawning of Lava Cats
        B:spawnLavaCat=false

        # Enable the spawning of Owls.
        B:spawnOwl=true
    }

    ##########################################################################################################
    # deer
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Deer
    ##########################################################################################################

    deer {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            FOREST
            COLD
            CONIFEROUS
            PLAINS
         >

        # Maximum number of deer to spawn in a group
        I:max=4

        # Min number of deer to spawn in a group
        I:min=2

        # Spawn rate of deer
        I:rate=6
    }

    ##########################################################################################################
    # fox
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Foxes
    ##########################################################################################################

    fox {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            FOREST
            COLD
            CONIFEROUS
         >

        # Maximum number of fox to spawn in a group
        I:max=3

        # Min number of fox to spawn in a group
        I:min=1

        # Spawn rate of fox
        I:rate=4
    }

    ##########################################################################################################
    # beetle
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Beetle
    ##########################################################################################################

    beetle {
        # Biome types to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            SWAMP
            JUNGLE
            FOREST
            PLAINS
         >

        # Maximum number of beetles to spawn in a group
        I:max=4

        # Min number of beetles to spawn in a group
        I:min=2

        # Spawn rate of beetle
        I:rate=5
    }

    ##########################################################################################################
    # frog
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Frog
    ##########################################################################################################

    frog {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            SWAMP
            JUNGLE
            BEACH
            RIVER
         >

        # Maximum number of frogs to spawn in a group
        I:max=4

        # Min number of frogs to spawn in a group
        I:min=2

        # Spawn rate of frog
        I:rate=6

        # How often slime balls are dropped; set to -1 to disable slime ball dropping
        I:slimeTime=18000
    }

    ##########################################################################################################
    # sprout
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Sprout
    ##########################################################################################################

    sprout {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            JUNGLE
            LUSH
            MAGICAL
            RIVER
            FOREST
            BEACH
         >

        # Maximum number of sprouts to spawn in a group
        I:max=4

        # Min number of sprouts to spawn in a group
        I:min=2

        # Spawn rate of sprouts
        I:rate=2
    }

    ##########################################################################################################
    # endermini
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of Endermini
    ##########################################################################################################

    endermini {
        # Maximum number of enderminis to spawn in a group
        I:max=1

        # Min number of enderminis to spawn in a group
        I:min=1

        # Spawn rate of enderminis in the End
        I:rate=50
    }

    ##########################################################################################################
    # owl
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of owls
    ##########################################################################################################

    owl {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            CONIFEROUS
            SPOOKY
            MAGICAL
            FOREST
            MOUNTAIN
            SNOWY
         >

        # Maximum number of frogs to spawn in a group
        I:max=3

        # Min number of owls to spawn in a group
        I:min=1

        # Spawn rate of owls
        I:rate=9
    }

    ##########################################################################################################
    # silkworm
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of silkworms
    ##########################################################################################################

    silkworm {
        # Set to false to disable silkworms entirely
        B:enabled=false

        # Specify a chance (1 in X) per chunk for a silkworm to grow (default 40, around 3-4 minutes per)
        I:growthChance=85

        # Specify a chance (1 in X) for silkworm eggs to drop when leaves are broken
        I:leafDropChance=55

        # Set to false to disable silkworm eggs from dropping when leaves are broken
        B:leafDrops=false

        # Specify a chance (1 in X) for silkworm eggs used to successfully spawn a silkworm
        I:successChance=2
    }

    ##########################################################################################################
    # lavacat
    #--------------------------------------------------------------------------------------------------------#
    # Controls the spawn settings of lava cats
    ##########################################################################################################

    lavacat {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            NETHER
         >

        # Maximum number of sprouts to spawn in a group
        I:max=0

        # Min number of sprouts to spawn in a group
        I:min=0

        # Spawn rate of lava cats
        I:rate=0
    }

    ##########################################################################################################
    # burnt trees
    #--------------------------------------------------------------------------------------------------------#
    # Spawn options for burn trees
    ##########################################################################################################

    "burnt trees" {
        # Excluded biomes types. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:"Excluded biome types" <
            VOID
            END
            WATER
            BEACH
            MESA
            MUSHROOM
            NETHER
            OCEAN
            RIVER
         >

        # Attempts to spawn a tree per chunk
        # Min: 1
        # Max: 2147483647
        I:"Spawn attempts"=1

        # Chance (1 in X) of burnt trees spawning; set to -1 to disable
        # Min: -1
        # Max: 2147483647
        I:"Spawn chance"=0
    }

    ##########################################################################################################
    # gold
    #--------------------------------------------------------------------------------------------------------#
    # Mystical world gold dusts
    ##########################################################################################################

    gold {
        # Enable Dusts for Gold
        B:enableDusts=false

        # Enable Tiny Dusts for Gold
        B:enableTinyDusts=false
    }

    ##########################################################################################################
    # iron
    #--------------------------------------------------------------------------------------------------------#
    # Mystical world iron dusts
    ##########################################################################################################

    iron {
        # Enable Dusts for Iron
        B:enableDusts=false

        # Enable Tiny Dusts for Iron
        B:enableTinyDusts=false
    }

    ##########################################################################################################
    # amethyst
    #--------------------------------------------------------------------------------------------------------#
    # Mystical world gems and their components
    ##########################################################################################################

    amethyst {
        # Enabled Amethyst
        B:enableAmethyst=true

        # Enable blocks of Amethyst
        B:enableBlocks=true

        # Enable gems of Amethyst
        B:enableGems=true

        # Enable Amethyst ore
        B:enableOres=true
    }

    ##########################################################################################################
    # copper
    #--------------------------------------------------------------------------------------------------------#
    # Mystical world copper options
    ##########################################################################################################

    copper {
        # Enable Blocks for Copper
        B:enableBlocks=false

        # Enable Copper
        B:enableCopper=false

        # Enable Dusts for Copper
        B:enableDusts=false

        # Enable Ingots for Copper
        B:enableIngots=false

        # Enable Nuggets for Copper
        B:enableNuggets=false

        # Enable Ores for Copper
        B:enableOres=false

        # Enable Tiny Dusts for Copper
        B:enableTinyDusts=false
    }

    ##########################################################################################################
    # silver
    #--------------------------------------------------------------------------------------------------------#
    # Mystical world silver options
    ##########################################################################################################

    silver {
        # Enable Blocks for Silver
        B:enableBlocks=false

        # Enable Dusts for Silver
        B:enableDusts=false

        # Enable Ingots for Silver
        B:enableIngots=false

        # Enable Nuggets for Silver
        B:enableNuggets=false

        # Enable Ores for Silver
        B:enableOres=false

        # Enable Silver
        B:enableSilver=false

        # Enable Tiny Dusts for Silver
        B:enableTinyDusts=false
    }

    ##########################################################################################################
    # toolenable
    #--------------------------------------------------------------------------------------------------------#
    # Tool/Weapon Enablind
    ##########################################################################################################

    toolenable {
        # Set to false to disable amethyst tool recipes entirely
        B:"Enable amethyst tools"=false

        # Set to false to disable copper tool recipes entirely
        B:"Enable copper tools"=false

        # Set to false to disable silver tool recipes entirely
        B:"Enable silver tools"=false

        ##########################################################################################################
        # amethyst tool recipes
        #--------------------------------------------------------------------------------------------------------#
        # Settings for individual Amethyst tool recipes
        ##########################################################################################################

        "amethyst tool recipes" {
            # Set to false to disable the amethyst axe recipe
            B:"Enable amethyst axe"=true

            # Set to false to disable the amethyst hoe recipe
            B:"Enable amethyst hoe"=true

            # Set to false to disable the amethyst knife recipe
            B:"Enable amethyst knife"=true

            # Set to false to disable the amethyst pickaxe recipe
            B:"Enable amethyst pickaxe"=true

            # Set to false to disable the amethyst shovel recipe
            B:"Enable amethyst shovel"=true

            # Set to false to disable the amethyst sword recipe
            B:"Enable amethyst sword"=true
        }

        ##########################################################################################################
        # copper tool recipes
        #--------------------------------------------------------------------------------------------------------#
        # Settings for individual Copper tool recipes
        ##########################################################################################################

        "copper tool recipes" {
            # Set to false to disable the copper axe recipe
            B:"Enable copper axe"=true

            # Set to false to disable the copper hoe recipe
            B:"Enable copper hoe"=true

            # Set to false to disable the copper knife recipe
            B:"Enable copper knife"=true

            # Set to false to disable the copper pickaxe recipe
            B:"Enable copper pickaxe"=true

            # Set to false to disable the copper shovel recipe
            B:"Enable copper shovel"=true

            # Set to false to disable the copper sword recipe
            B:"Enable copper sword"=true
        }

        ##########################################################################################################
        # silver tool recipes
        #--------------------------------------------------------------------------------------------------------#
        # Settings for individual Silver tool recipes
        ##########################################################################################################

        "silver tool recipes" {
            # Set to false to disable the silver axe recipe
            B:"Enable silver axe"=true

            # Set to false to disable the silver hoe recipe
            B:"Enable silver hoe"=true

            # Set to false to disable the silver knife recipe
            B:"Enable silver knife"=true

            # Set to false to disable the silver pickaxe recipe
            B:"Enable silver pickaxe"=true

            # Set to false to disable the silver shovel recipe
            B:"Enable silver shovel"=true

            # Set to false to disable the silver sword recipe
            B:"Enable silver sword"=true
        }

    }

    ##########################################################################################################
    # oredebugging
    #--------------------------------------------------------------------------------------------------------#
    # Ore Debugging Options
    ##########################################################################################################

    oredebugging {
        # Enable the debugging of Amethyst Ore
        B:"Debug Amethyst Ore"=false

        # Enable the debugging of Copper Ore
        B:"Debug Copper Ore"=false

        # Enable the debugging of Silver Ore
        B:"Debug Silver Ore"=false

        # Enable debugging at all. Specific ores will need to be enabled individually before any messages will be printed.
        B:"Enable Debugging"=false

        # Enable debugging to the standard log file. Useful if you do not generate or have access to debug.log. WARNING: WILL OVERLY INFLATE YOUR STANDARD LOG FILE. ONLY ENABLE IF NEEDED.
        B:"Enable Info Debugging (ONLY IF NEEDED)"=false
    }

    ##########################################################################################################
    # oregen
    #--------------------------------------------------------------------------------------------------------#
    # Controls ore generation for Mystical World Ores.
    ##########################################################################################################

    oregen {
        # The highest an amethyst ore vein can generate
        # Min: 0
        # Max: 255
        I:amethystMaxY=32

        # The lowest an amethsyt ore vein can generate
        # Min: 0
        # Max: 255
        I:amethystMinY=5

        # The amount of amethyst veins to generate per chunk. Set to 0 to disable.
        I:amethystPerChunk=2

        # The maximum size of an amethyst ore vein.
        I:amethystVeinSize=5

        # The highest a copper ore vein can generate.
        # Min: 0
        # Max: 255
        I:copperMaxY=64

        # The lowest a copper of vein can generate.
        # Min: 0
        # Max: 255
        I:copperMinY=0

        # The amount of copper veins to generate per chunk. Set to 0 to disable.
        I:copperPerChunk=6

        # The maximum size of a copper ore vein.
        I:copperVeinSize=12

        # List of dimensions to spawn ore in (default 0)
        S:dimensions <
            0
         >

        # The highest a silver ore vein can generate.
        # Min: 0
        # Max: 255
        I:silverMaxY=28

        # The lowest a silver of vein can generate.
        # Min: 0
        # Max: 255
        I:silverMinY=0

        # The amount of silver veins to generate per chunk. Set to 0 to disable.
        I:silverPerChunk=4

        # The maximum size of a silver ore vein.
        I:silverVeinSize=8
    }

}


<

This seems to have been the problem as I haven't been able to replicate the crash since I reinstalled the mod and refreshed the config file. Strangely, it seems that lava cats are still spawning after attempting to remove them via mod options, but it's not the end of the world I guess.

Thanks for your legendary response time, much applause! :)

**Comment by noobanidus** [comment]
I've added some code for it and that should be in the next release.
