### ISSUE TITLE
Ehh...unrealised mobs?

### ISSUE THREAD

**Issue by guide-for-you** [MysticMods/MysticalWorld#194]
![2020-08-24_12 45 29](https://user-images.githubusercontent.com/53404970/91030831-6d885700-e608-11ea-85f1-bf5d2ca47c2d.png)

**Comment by guide-for-you** [comment]
Lurker and Clam

**Comment by noobanidus** [comment]
That is definitely an OOPS. Yeah, I forgot to remove them from being registered, although they have no spawn conditions and you can only access them in creative.

**Comment by noobanidus** [comment]
So, the lurker is being removed, the clam is TBI.
