### ISSUE TITLE
Please add forge:tools/knife to knives.

### ISSUE THREAD

**Issue by Divineaspect** [MysticMods/MysticalWorld#200]
**Describe your suggestion:**
Please add forge:tools/knife to knives.

**Describe alternatives you've considered:**
This would allow your knives to be compatable with other knife recipes without a datapack,

**Additional context:**
Noticed this while playing with farmer's delight.

**Comment by noobanidus** [comment]
I'll try to include this in the next release!

**Comment by noobanidus** [comment]
Coded and should be included in the next release!
