### ISSUE TITLE
Game crash related to Ghost Deer: Ticking Entity

### ISSUE THREAD

**Issue by RisingInIris2017** [MysticMods/MysticalWorld#201]
### General Information

**Describe the bug:**

When a Ghost Deer came and ran into me, the game crashed.

**To Reproduce:**

I have not reproduced this issue, but I will try to do so if needed.

**Expected behavior:**

The deer should heal me but not lead to game crash.
***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: mysticallib-1.12.2-1.9.0
- mysticalworld-1.12.2-1.9.2

**Other Versions:**
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

***
**Crash Report (if available):**
https://paste.ubuntu.com/p/945VrNvswC/
***
This issue is something that I happened to run into.
If further testing is needed, I will try to do so and provide you any information you need.
Thanks for your help  in advance!

**Comment by noobanidus** [comment]
That's an odd one! I'll look into it.
