### ISSUE TITLE
Rotten Apples not working on villagers.

### ISSUE THREAD

**Issue by AnotherVagabond** [MysticMods/MysticalWorld#203]
### General Information

**Describe the bug:**
Attempting to use a rotten apple on a villager (both with and without a job, while crouching and while not) attempts to trade with that villager instead of using the apple on it.

**To Reproduce:**
1. Obtain rotten apple.
2. Attempt to use rotten apple on villager.
3. Fail.

**Expected behavior:**
The apple is consumed and there is a chance the villager becomes a zombie villager.

***

### Environment Versions
**Mystic Mods Versions**

- Mystical World: 0.3.1.1

**Other Versions:**
- Forge: 35.1.0
- Minecraft: 1.16.4
- Modpack (if available): Vanilla plus Mystical World and Patchouli.

**Comment by noobanidus** [comment]
I wanna rethink this so I'm going to remove the rotten apple for now.
