### ISSUE TITLE
lava cat's and hell sprouts not spawning 1.16.4-0.3.1.

### ISSUE THREAD

**Issue by FurryApocalypse** [MysticMods/MysticalWorld#204]
As above. We started the server several times to check if it's repeating. In fact while scavenging nether there was not a single one lava cat in nether. Same with the hell sprouts. After 2 times i changed the spawn chance in config to check if it's  so rare and i had no luck or its just not working. Another two clean worlds were created and also not found them in nether. 
Endermini seems to work fine and spawn naturally in single player (not tested in server)
We're using forge 35.1.4

**Comment by noobanidus** [comment]
Okay, that's interesting, I thought I'd confirmed it.

**Comment by FurryApocalypse** [comment]
Patchouli is installed from the link without MysticalLib (couse it says there is no need) - Im just sayin in case it is helpful

**Comment by noobanidus** [comment]
Thanks! Yeah, the spawn rates might be too rare. I need to triple-check it.

**Comment by noobanidus** [comment]
This should be installed from the next version.
