### ISSUE TITLE
Silver Fox Crashed The Game?

### ISSUE THREAD

**Issue by KamikazePigeon** [MysticMods/MysticalWorld#206]
So I was playing a LAN game with my sister and we came across some Silver Foxes. She tamed one, and everything went as normal. It died, so she tamed another, same thing. When she went to tame a third, the game crashed in the taming process and left us with this error report. 

We've decided to just leave the foxes alone because of it since we don't know what causes it, especially since the foxes are all crippled as well (when tamed they lay down and get stuck there until you hit them, and even then their front legs don't go back to normal, staying in the sleeping position). I saw someone else mentioned this, so this is a known bug. But the crash isn't, and I wanted to see if someone could decipher this crash report.

Using the latest versions of both Forge and Mystical World.

[crash-2020-12-15_18.39.42-client.txt](https://github.com/MysticMods/MysticalWorld/files/5700646/crash-2020-12-15_18.39.42-client.txt)

![Crash](https://user-images.githubusercontent.com/75771054/102311332-8acb9300-3f21-11eb-9537-0a554dea344e.jpg)

**Comment by noobanidus** [comment]
Did you use a golden apple by any chance?

It looks as though the code to *heal* a previously-tamed creature is susceptible to null... I know that there was a recent PR that specifically added itemstack-sensitive variants of `getFood` so I'm not sure if that's part of the issue or not. I'll look into it, thanks!

**Comment by KamikazePigeon** [comment]
Nope, no golden apples. She actually went out and broke the oak trees specifically for apples just before taming it.

**Comment by noobanidus** [comment]
Thanks! That makes a lot more sense. I should be able to reproduce one my environment stops being broken.

**Comment by KamikazePigeon** [comment]
Little mini update! I talked to my sister, and apparently it crashed DIRECTLY upon attempting to feed an apple to her already tamed fox. So what you said about that holds up.

**Comment by k0k0nutttt** [comment]
I tried killing a silver fox and it crashed my game on my server, is there a way to stop spawning them or to fix this issue? I'm on 1.15.2

**Comment by noobanidus** [comment]
@k0k0nutttt Please open a new issue and include your crash report.

**Comment by noobanidus** [comment]
@k0k0nutttt 1.15.2 isn't really supported at this point. Please open a new issue and include the crash log.
