### ISSUE TITLE
Tamed Beetle wont Mount

### ISSUE THREAD

**Issue by Marihenshin** [MysticMods/MysticalWorld#207]
### General Information

**Describe the bug:**
Tamed beetles can be sneak-right-clicked in order to mount them on your shoulder 
Dose not Work

tamed with Melon Slice and with the Seeds and the Beetle Stairs at me but will not mount if Sneaking and right clicking

**Mystic Mods Versions**
mysticalworld-1.16.4-0.3.1.1.jar

**Other Versions:**

- Forge: 35.1.13
- Minecraft: 1.16.4

**Comment by noobanidus** [comment]
I may not have made this clear enough in the documentation, but with the changes to rendering in 1.15 I wasn't able to port this feature.
