### ISSUE TITLE
Cannot Add Mining Dimension?

### ISSUE THREAD

**Issue by celsiusqc** [MysticMods/MysticalWorld#209]
### General Information

**Describe the bug:**

Trying to add the dimension from the mod Mining Dimension for ore generation, but cannot seem to get it working

Any way of blacklisting dimensions instead of whitelisting ? Simple to blacklist the end and the nether

**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft: 1.16.4
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Can you show a copy of the configuration that you've tried?

You need the identifier of the dimension in the form of `modid:dimension_name`.

**Comment by noobanidus** [comment]
If you're still having this issue, I need to see the configuration file you're using and the mining dimension mod in order to try replicating. Please file a new issue.
