### ISSUE TITLE
1.16.4: Player has invisible fortune, all the time.

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#212]
### General Information

**Describe the bug:**
Players (i.e, me in singleplayer) are experiencing Fortune effects while breaking ores like coal, redstone, etc, with freshly-crafted unenchanted pickaxes.

**To Reproduce:**
1. Construct Pack (versions in Version section)
2. Create World
3. Find (or spawn) Coal Ore
4. Place and mine until one of them drops two coal (I spawned in my wooden_pickaxe but I don't think it matters)

**Expected behavior:**
Uh, not this. I assume this is an oversight with Serendipity, or something. 
***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: None :) 
- MysticalWorld: 1.16.4 - 0.3.1.2

**Other Versions:**
- Forge: 35.1.13
- Minecraft: 1.16.4
- Patchouli: 1.16.4-48
(patchouli isn't relevant here, it's just a required dependency)

rest of template snipped, as there were no obvious errors in the log nor a crash

**Comment by noobanidus** [comment]
Oops. I checked the modifiers when I got up and it turns out that the default was "min: 1, default: 1", instead of 0, 0. Should be fixed in the next release.
