### ISSUE TITLE
[1.16.4] Aubergines are not tagged as 'vegetables'

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#213]
### General Information

**Describe the bug:**
Aubergines aren't tagged in the generic 'vegetables' forge tag, rendering them unusable for other mod recipes which would otherwise take any vegetable.

**Expected behavior:**
I would expect to be able to use aubergines to make the ratatouille from Farmer's Delight... _alas._

***

### Environment Versions
Forge 35.1.13
Mystical World 1.16.4-0.3.1.2

**Comment by noobanidus** [comment]
That's weird, I swear I did that.

**Comment by noobanidus** [comment]
Okay, I added vegetables but forogot to put aubergines in it.
