### ISSUE TITLE
[1.16.4] Spindle gets entirely consumed when crafted with cocoons instead of losing durability

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#214]
### General Information

**Describe the bug:**
Crafted a freshly-created spindle with a silk cocoon; the spindle was consumed in its entirety.

**To Reproduce:**

1. Obtain cocoon
2. Obtain spindle
3. Craft cocoon with spindle
4. Watch as the spindle magically disappears when you take the output silk string
5. 
**Expected behavior:**
In previous versions of Mystical World, the spindle only took durability damage. The patchouli documentation also seems to indicate this is still intended to be the case.

***

### Environment Versions

**Mystic Mods Versions**
1.16.4-0.3.1.2

**Other Versions:**
- Forge: 35.1.13
- Minecraft: 1.16.4

**Comment by noobanidus** [comment]
Recipes... don't seem to work any more.

**Comment by noobanidus** [comment]
This will be fixed in the next release.
