### ISSUE TITLE
Aubergine Seed Drop Config Toggle

### ISSUE THREAD

**Issue by HenryMaxler** [MysticMods/MysticalWorld#217]
**Describe your suggestion:**
I wanted a way to configure the aubergine seeds to not drop when harvesting tall grass

**Describe alternatives you've considered:**
Tried looking at config but didn't see it there, but everything else was there

**Comment by noobanidus** [comment]
What version of Minecraft is this for?

In 1.14 onwards you can use a native datapack to replace the grass injection table in the Mystical World datapack.

In 1.12, there are mods that allow you to modify the drop table of grass.

**Comment by HenryMaxler** [comment]
Its for 1.16.4.  Yeah, I'm looking for a solution that works across multiple worlds, and that I could even make a modpack that has the config file.  As far as I can tell, the datapacks you'd have to put in each world separate?  Crafttweaker I don't believe has the seeds module for 1.16.4...

**Comment by noobanidus** [comment]
Look into Open Loader or some other datapack loader to auto-inject your datapacks.

I am looking into changing how aubergine seeds drop but at the minute they're an integral part of the mod and, while I'm one to offer functionality when there's no other way to disable it, there are a bunch of options for disabling them outside of the pack.

**Comment by HenryMaxler** [comment]
Oh I see, thank you.

**Comment by noobanidus** [comment]
I'd recommend looking up guidies on how to make a datapack. They're a vanilla system so there should be plenty.

**Comment by HenryMaxler** [comment]
Working now, thanks for the help
