### ISSUE TITLE
Gold tools missing piglin tag

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#218]
### General Information
**Describe the bug:**

- Gold tools are missing the item tag `minecraft:piglin_loved`.

**To Reproduce:**

1. Check tags for piglins

**Expected behavior:**

- For gold tools to have the tag.

***

### Environment Versions

**Mystic Mods Versions**

`Mystical World v0.3.1.4`

**Other Versions:**
`Minecraft v1.16.4`
`Forge v35.1.28`

**Comment by noobanidus** [comment]
Thanks, I'd missed this!

**Comment by WenXin20** [comment]
No problem! A lot of mods seem to miss this tag, you're not the only one. :D

**Comment by noobanidus** [comment]
A lot of it probably has to do with unfamiliarity with all of the new 1.16 mechanisms as well as directly porting from 1.15. Definitely the reason why I missed it!

**Comment by WenXin20** [comment]
Ah true. I only just found out about the tag myself, and then saw I wasn't the only one. :D

**Comment by noobanidus** [comment]
This was done in 2d690a5ae9be7b.
