### ISSUE TITLE
Mixin warning at startup

### ISSUE THREAD

**Issue by toktoktheeo** [MysticMods/MysticalWorld#219]
Hi,

**Describe the bug:**
I got this in the log at startup: [11:58:36] [main/WARN] [mixin/]: Reference map 'mysticalworld.refmap.json' for mysticalworld.mixins.json could not be read. If this is a development environment you can ignore this message>

I don't know if this is a bad thing. But I wanted to let you know.

**To Reproduce:**
Start the instance.

**Expected behavior:**
To not have a warning.

**Mystic Mods Versions**

Mystical World 0.3.1.4

**Other Versions:**

- Forge: 35.1.28
- Minecraft: 1.16.4

Have a nice day.

**Comment by noobanidus** [comment]
Ah, that's a mistake in the template. Mystical World doesn't currently use mixins.

**Comment by toktoktheeo** [comment]
I'm relieved. Thanks for your time. ;-)

**Comment by noobanidus** [comment]
My fault for being over-enthusiastic with the copy/paste! I'll leave this open in case anyone else is concerned.
