### ISSUE TITLE
Feature Request: use item tag gem:amethyst for Serendipity potion brewing

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#220]
**Describe your suggestion:**
For modpacks that add multiple varieties of amethyst and may be defaulting to a variety from worldgen/etc other than Mystical World's, it would be great if those other variants were usable for the potion brewing process, since they can already be used for MW's amethyst armor/tools.

**Comment by Birgliss** [comment]
(for clarity, i believe the specific tag is forge:gems/amethyst)

**Comment by noobanidus** [comment]
Done!
