### ISSUE TITLE
Capability being accessed before @CapabilityInject is firing

### ISSUE THREAD

**Issue by zetilion** [MysticMods/MysticalWorld#221]
Im playing on valhesia 3 where are the mod of Mystical World what go with conflict with the preview version of optfine i will link pastebin of report crash of mc: https://pastebin.com/K1yv4ZeL

**Comment by noobanidus** [comment]
Does it crash without optifine?

**Comment by zetilion** [comment]
> Does it crash without optifine?

Gimme a sec and i try

**Comment by zetilion** [comment]
nope it not crash

**Comment by noobanidus** [comment]
I'm afraid you'll need to report this to Optifine then.

**Comment by Vaelzan** [comment]
I know you just closed this, but I can confirm that this error occurs at random WITHOUT OptiFine too.

**Comment by Vaelzan** [comment]
I can see that they're running Valhelsia, but I've been able to reproduce an essentially identical (-OptiFine) crash log in the same pack version (Valhelsia 3.1.4). It doesn't happen upon every startup.

**Comment by noobanidus** [comment]
@Vaelzan Ah, thanks, that's what I needed to know. Can I grab a copy of the crash report without Optifine?

**Comment by noobanidus** [comment]
I think I've solved this in the commit I forgot to tag this bug in, 35e04cccc546.
