### ISSUE TITLE
[mysticalworld:main_network_channel] rejected their server side version number | mysticalworld-1.16.4-0.3.1.4.jar

### ISSUE THREAD

**Issue by cryzies** [MysticMods/MysticalWorld#222]
### General Information

**Describe the bug:**

[mysticalworld:main_network_channel] rejected their server side version number 
Mismatch issue on mysticalworld-1.16.4-0.3.1.4.jar even when mod is present on both client and server, deleting jar from client and server allows me to login

**To Reproduce:**

1. Install mysticalworld-1.16.4-0.3.1.4.jar on client and server

**Expected behavior:**

Mod to load without issue
***

### Environment Versions

1.16.4

**Mystic Mods Versions**

- mysticalworld-1.16.4-0.3.1.4.jar

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: forge-1.16.4-35.1.36.jar
- Minecraft: 1.16.4
- Modpack (if available): Valhelsia 3 v3.1.4 (and v3.1.4a)

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
https://gist.github.com/cryzies/2ea6e711b1c60eaca401d00d3faa563d (both client+server debug.log are there, longg)
**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Wow, that is a really strange bug. Let me see if I can reproduce in development.

**Comment by noobanidus** [comment]
Should be fixed in the .6 release coming soon on Curseforge.
