### ISSUE TITLE
Config options for armor values

### ISSUE THREAD

**Issue by phyne** [MysticMods/MysticalWorld#228]
**Describe your suggestion:**
Config options to set armor values (and possibly effect values) for copper, tin, lead, amethyst, silver, quicksilver armor sets.

**Describe alternatives you've considered:**
I work around it!

**Additional context:**
More granular control makes setting up a modpack with extra tiers of metals beyond vanilla easier to accomplish.

Please consider!

**Comment by noobanidus** [comment]
Is there no other way to adjust them?

**Comment by phyne** [comment]
Hell, you probably know more than me... As far as I know, only a mod like [Material Changer](https://www.curseforge.com/minecraft/mc-mods/material-changer) can do this. For instance, when I've used Armor Plus in the past, they've included config options for their weapons and armors.

**Comment by noobanidus** [comment]
The main issue is that most of the materials are statically initialized and I'm not sure if it's possible to set it up in a way that it's configurable, possibly making them lazy values. I'm working on the mod so I'll try to figure out something now.

**Comment by noobanidus** [comment]
I'm not sure if what I've done will work properly and I'm not ... super happy about it, as it sort of upsets the internal "balance" but it is optional after all. I'll try to include it in the next release.
