### ISSUE TITLE
Potion of Serendipity currently unbrewable

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#229]
### General Information

**Describe the bug:**
Amethysts cannot be used to create potions of serendipity, I suspect this has something to do with the implementation of #220 

Mystical World 1.16.4-0.3.1.6
Forge 35.1.28

**Comment by noobanidus** [comment]
Hmmmm.

**Comment by noobanidus** [comment]
That was frustrating to fix.
