### ISSUE TITLE
Crash on load in combination with Apathetic Mobs

### ISSUE THREAD

**Issue by jolandepoel** [MysticMods/MysticalWorld#23]
Your mod is lovely and I enjoy the little critters populating my world.  but then the game crashed. I'm playing Enigmatica 2, but always update everything to the latest version that works, including my forge version. 

It says Mystic World crashed, which is why I'm posting this here, but scanning the log, Apathetic Mobs seems to be the culprit instead. I've added Apathetic Mobs to my pack because I get really scared when mobs attack me. 
The issue I opened on the Apathetic Mobs issue tracker is here: https://github.com/whizzball1/ApatheticMobs/issues/6

These are the things I've tried:
I installed Apathetic Mobs without editing any of the config, and it worked.
But now I've changed the config to mobs taking revenge and I get a Mystic World crash, 
Disabling only Apathetic Mobs fixes it, disabling Mystic World (which automatically disabled Roots) fixes it, and disabling Revenge Mode fixes it. Enabling Revenge Mode but disabling the revenge timer still crashes it. 
Therefore, there seems to be an interaction between mobs taking 'revenge' and the Mystic World mobs, I think the issue is with Apathetic Mobs, but I wanted to let you know regardless.

Crash report: https://pastebin.com/exf1MX59

**Comment by EpicSquid** [comment]
Yeah their capability seems to be crashing the game when they add it to our mobs. It seems to be on them but I will leave the issue open till we know for sure.

**Comment by duely** [comment]
I've commented on the issue as I had a similar problem with Dude! Where's my Horse? a while back. This is specifically because we're instantiating entities with null worlds in order to propagate them into Just Enough Resources, but these entities are then having capabilities applied to them. They just need to bail whenever entity.world is null -- I think we can close this issue safely.

**Comment by jolandepoel** [comment]
Fixed!
