### ISSUE TITLE
Seeds not compostable

### ISSUE THREAD

**Issue by Alexthw46** [MysticMods/MysticalWorld#233]
### General Information

Aubergine seeds are not accepted by the composter (vanilla block).

The modlist for possible mod conflits is the Valhelsia 3.

**Comment by Alexthw46** [comment]
I'd add that the seeds seems to lack the "forge:seeds" tag since the recipes doesn'show up for them

**Comment by noobanidus** [comment]
From what I can tell, composting works perfectly in the development environment, so it sounds like another mod is conflicting somehow -- perhaps doing a registry replacement on the composter block or wiping the table.
