### ISSUE TITLE
Allow sprouts/aubergine to be toggled in config file

### ISSUE THREAD

**Issue by Powermonkey00** [MysticMods/MysticalWorld#234]
The aubergines cause issues with some other mods, being able to toggle them would be great as I hate to remove the whole mod from my modpack because of them.

**Comment by noobanidus** [comment]
a) Please clarify what version of Mystical World & Minecraft you're referring to.
b) Aubergines are basically an iconic part of Mystical World. Can you explain what issues you're having with other mods? 
c) Can you explain what you mean by being able to "toggle" them?

**Comment by noobanidus** [comment]
Without any further information, this isn't something I'm going to be able to take any action on. Please reply with more information and I'll re-open this ticket.
