### ISSUE TITLE
Deerhelmet causing lag on server

### ISSUE THREAD

**Issue by SaphieNyako** [MysticMods/MysticalWorld#236]
### General Information

**Describe the bug:**
Deerhelmet causes lag on my server.
Only 1 was in use.
Used up 20% of server thread.

**To Reproduce:**

1. Find a Deer and Kill it
2. Craft a helmet from it remains
3. Wear helmet and happy dead deer you just killed will heal you T_T

**Expected behavior:**
The deers spawning where spamming find path find path. 

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...
mysticalworld-1.16.4-0.3.1.6.jar
**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:35.1.36
- Minecraft:
- Modpack (if available): Feywild

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

![image](https://user-images.githubusercontent.com/77398437/105640303-9e054300-5e7d-11eb-839e-c83f9c605926.png)

**Additional context (optional):**

**Comment by noobanidus** [comment]
Thanks for the confirmation and the reminder, I forgot to open an issue myself. I'm going to convert this to using a particle isntead, hopefuully.

Recommandtion with spark: if you look in the top right there's a drop-down that allows you to select mappings, "MCPForge 1.6.4" should work with 1.16.5 also and help clear up which function is which.

**Comment by Vaelzan** [comment]
Just chiming in to say that I've had this happen in 1.15.2 as well, causing a server crash multiple times until we removed all the spirit deer + helmets. I just forgot to make the report when it was happening. No idea if you still fix 1.15.2 bugs but I can just blacklist the recipe in the pack if not.

**Comment by noobanidus** [comment]
I won't be making any changes to 1.15.2 at this point, sorry. It's too difficult to maintain multiple versions even when the codebase is otherwise identical.
