### ISSUE TITLE
Bug: Reoccurring bug in world gen of the burrows.

### ISSUE THREAD

**Issue by SirAron111** [MysticMods/MysticalWorld#24]
Bug: Reoccurring bug in world gen of the burrows.
They always seem to spawn on the building of lost cities so that means they generate after the buildings and don’t check for a a grass or dirt flooring. there are some normal oness around in some plains and so but its just the 4 time i saw this and found it funny
Doesn’t bother me much as I set them to low spawn rate anyway! Jut thought I would let you know.
![2019-08-03_18 12 12](https://user-images.githubusercontent.com/39855956/62414626-5605b700-b61e-11e9-88a8-d82b5228f112.png)

**Comment by duely** [comment]
Unfortunately Lost Cities doesn't really inform anyone as to whether or not it's been spawned in that location or not. I'll look into checking specifically for grass, but that will unfortunately limit the placement of these structures even more than currently.

**Comment by duely** [comment]
I've added checks for grass and dirt, though they will need to be refactored for future placement types. Unfortunately it will artificially inflate the rarity of these structures even further, but we'll see how it turns out.

**Comment by SirAron111** [comment]
It did prevent the spawning on top of buildings but also made them really rare if nonexistent at all. Like for example I had to set the generation chance to below 100 to find one! Before I had the setting to 600 and there were like 1 borrow and one hut in every plains biome sometimes 2

Wouldn’t simply blacklisting the structure spawn onto of concrete or ordicted concrete (in case of chisel mod) blocks have done? So if the structure gen event fires and it decided that the roll was a success spawning the structure right before structure would spawn it checks if it would spawn on concrete and if it does it won’t spawn. Or something like that.

Because currently I think its looking for enough flat area grass with a deep enough dirt layer under to spawn. But mostly stone layer starts at some point and they become really rare
I have no idea how to code so I could be totally wrong about this. But they do spawn way less now.
