### ISSUE TITLE
Look-over for knockback resist values on Lead Armor

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#241]
wiping template as issue was discussed in discord

knockback resist on lead armor seems to be inconsistent with values present in vanilla  
for example, each piece of Netherite armor gives you +1 knockback resistance
but lead boots give you +20 knockback resistance

**Comment by GreyMario** [comment]
Have you _tried_ putting on a pair of lead boots? This is some Legend of Zelda shit right there.

**Comment by noobanidus** [comment]
So, I'm happy for them to have more than netherite but not that much more. Going to adjust the values on each piece.
