### ISSUE TITLE
Male Deer report

### ISSUE THREAD

**Issue by HatcheryRoosters** [MysticMods/MysticalWorld#244]
This mainly focuses on deer breeding

The male deer are the ones producing fawns.

Males can also be bred with other males, same with females

We should be breeding bucks with does with the does dropping the babies

**Comment by noobanidus** [comment]
Antlers are a cosmetic value, not a gender value. Otherwise, breeding takes place precisely as vanilla logic dictates, with the parent of the offspring being whichever one you first bred (I believe).

No intention of coding any gender into the deer at this time, sorry.

**Comment by elucent** [comment]
deer are canon bi. i dont make the rules
