### ISSUE TITLE
Stacked Slab Issues

### ISSUE THREAD

**Issue by CodexArchive** [MysticMods/MysticalWorld#252]
### General Information

**Describe the bug:**
- After breaking any full block from Mystical World assembled by stacking 2 slabs, only one slab of the respective material is returned instead of 2
- When thatch slabs are stacked, the resulting full block has black boxes along the textures that fall outside of the block's main space
- When either Brown Mushroom or Mushroom Stem slabs are stacked, the block only has a texture for the north-facing side which provides a limited x-ray on all other sides

**To Reproduce:**
1. Stack slabs to create full blocks
2. Observe broken textures
3. Break full blocks and only receive single slab instead of 2

**Expected behavior:**
- Broken slab stacks returning both slabs on break
- Non-broken textures on thatch and mushroom slab full blocks

**Mystic Mods Versions**
- MysticalLib: 1.16.4-0.3.1.9
- Patchouli: 1.16.4-50

**Other Versions:**
- Forge: 1.16.4-35.1.37
- Minecraft: 1.16.4

### Additional Information
**Screenshots (if available):**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80467605/111069475-99373580-84a3-11eb-9225-ca193ec724ec.png">

**Comment by noobanidus** [comment]
Huh! That's really weird, thanks for the information. I'll look into it.

**Comment by noobanidus** [comment]
By the look of it, I'm using the wrong base block for the thatch double-slab -- it should be creating the "simple" slab instead of the big double.

As to why the others are happening, I'm not so certain.

**Comment by noobanidus** [comment]
This should be fixed in the most recent release.
