### ISSUE TITLE
Clams cannot be killed

### ISSUE THREAD

**Issue by guide-for-you** [MysticMods/MysticalWorld#254]
https://user-images.githubusercontent.com/53404970/112724544-906f4680-8f1c-11eb-942a-68f3ba36fe02.mp4

**Comment by Kinnyth** [comment]
I have the same issue

**Comment by noobanidus** [comment]
I'll try to get a release fix out for this soon.

**Comment by noobanidus** [comment]
Hopefully this is fixed in the release that just went out.
