### ISSUE TITLE
Food recipes

### ISSUE THREAD

**Issue by Hequinoxe** [MysticMods/MysticalWorld#255]
**Describe your suggestion:**
About the stuffed aubergine and the venison recipes, I really like the idea but they are powerful vs vanilla recipes. And aubergine is basically everywhere. Would it be possible to add some config to adjust it, please? A couple of idea: adjust the frequency of aubergine seed drop, recipe hunger and saturation level adjust. 

**Describe alternatives you've considered:**
Maybe a boolean to remove spawning of Aubergine and Loot Venison but that would be a shame since they add to the game. But it might be easier to add, I think.

**Additional context:**
Nothing I can think of.

Thanks!

**Comment by noobanidus** [comment]
There's already an issue opened for this.

**Comment by noobanidus** [comment]
#242

You can also remove the recipes with a data pack.
