### ISSUE TITLE
[1.12] Silkworm eggs are Spawn eggs, and thus when used on a vanilla spawner change it's output.

### ISSUE THREAD

**Issue by Divineaspect** [MysticMods/MysticalWorld#256]
### General Information

**Describe the bug:**

Silkworm eggs are Spawn eggs, and thus when used on a vanilla spawner change it's output.

**To Reproduce:**

1. Use a silkworm 
2. Watch it spawn silkworms

**Expected behavior:**

Probably shouldn't do that.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Mystical world: 0.3.1.9
- 
**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 36.0.58
- Minecraft: 1.16.5
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Yeah, I need to change these items to not be spawn eggs. Laziness didn't help me here.

**Comment by noobanidus** [comment]
This is fixed in 1.16. I'll still need to fix it in 1.12.

**Comment by noobanidus** [comment]
They appear to be ItemBase-derived in 1.12.2, so it doesn't need to be resolved there.
