### ISSUE TITLE
[1.12.2] Squids/Clams rarely... if ever... spawn.

### ISSUE THREAD

**Issue by Z-Tunic** [MysticMods/MysticalWorld#257]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 10
BiomesOPlenty-1.12.2-7.0.1.2444-universal
CodeChickenLib-1.12.2-3.2.3.358-universal
CoFHCore-1.12.2-4.6.6.1-universal
CoFHWorld-1.12.2-1.4.0.1-universal
jei_1.12.2-4.16.1.302
mysticallib-1.12.2-1.10.0
mysticalworld-1.12.2-1.9.5
Patchouli-1.0-20
RedstoneFlux-1.12-2.1.1.1-universal
Roots-1.12.2-3.0.33

=====

I dunno if COFH, CodeChickenLib or RedstoneFlux are needed but I included those while trying to narrow down the cause.

For some weird reason I can barely, if ever... find any Squids or Clams with worlds using the Biomes O' Plenty world type. There's a chance that there may be a world where they will spawn at first but as you go exploring the world... you'll notice that they will rarely, if ever spawn.

I have included a screenshot with having Roots & Mystical World added and a screenshot without those two mods added.

![](https://cdn.discordapp.com/attachments/377171551155650560/834057870810284062/nosquidsorclamswithrootsmysticalworld.PNG)
In this screenshot, I flew around in creative and haven't seen any Squids or Clams in the water. Biome is Ocean which is a biome that is whitelisted in the Mystical World config by default for Clams.

![](https://cdn.discordapp.com/attachments/377171551155650560/834057906101682247/squidswithoutrootsmysticalworld.PNG)
I removed Roots & Mystical World & flew around again and noticed that Squids were spawning as usual. I tried to follow the exact steps that I did in the previous screenshot.

For a further test... I downgraded these mods...

mysticallib-1.12.2-1.9.0
mysticalworld-1.12.2-1.9.2
Roots-1.12.2-3.0.32

...and squids still spawn as they should, minus the clams as they weren't present in these versions. Even in my modded survival world which has about 300+ mods... they spawned as usual. The above screenshots were taken with much less mods.

In case if needed, this is the world seed I was using to get the above screenshots.
-199402479460164806

*EDIT*
This also occurs with the Vanilla World Type however squids DO spawn at your starting point if you use the above world seed but if you fly around the world... no squids will spawn... if ever.

**Comment by noobanidus** [comment]
That's really interesting. Can you try disabling clams from spawning completely and see if that affects the spawn rate of squids?

i.e., having all of the mods you mentioned installed, but having clams disabled. You can do this in the "clam" section of the "mysticalworld.cfg" file, setting "I:rate=14" to "I:rate=0".

I'm curious to see if I'm impacting on the overall underwater spawns or if the default spawn rate is just too high for clams that it's crowding out Squid spawns -- but not actually spawning any clams for whatever reason.

**Comment by noobanidus** [comment]
(And I do not think any of the other mods should be affecting this, this is obviously an issue with MysticalWorld.)

**Comment by Z-Tunic** [comment]
Setting the rate to 0 and tested on a world with only the above mods installed and then my heavily modded world with about 300+ mods installed... I can confirm that squids will spawn normally.

**Comment by Z-Tunic** [comment]
jei_1.12.2-4.16.1.302
mysticallib-1.12.2-1.10.0
mysticalworld-1.12.2-1.9.8
Patchouli-1.0-23.6
Roots-1.12.2-3.0.35

=====

Max/Min config options aren't working correctly as both are set to 1 by default and I've seen 2-4 clam groups spawn in.

It seems that Rate: 5 is apparently still high as I only see clams spawning with a rare chance of some squids, although setting it to 1 allows squids to spawn as well as clams. How I was able to test this was by doing "@e[type=!player]" which kills all mobs besides the player and waiting for the spawns to occur.

There is a way I can 'force' them to spawn by doing a "/kill @e[type=!player]" which kills all the entities in the area, only then will the squids/clams spawn in that area but once I move to a different part of the map... they still may not spawn. I'll try to see if Rate: 1 helps with that in a way.

**Comment by noobanidus** [comment]
Unfortunately, the min/max is something I can't really control: those values are being added to the RegistryEntry as min and max (I just triple-confirmed it), but it may have something to do with the placement type or the creature type that is causing them to cluster up in groups: if those are the only eligible locations...

Feel free to reduce below 5. In my test, dev world, I was using `/forge entity list` to get a rough count of clams versus squids, and I noticed that there were significantly more squids spawning (they have a spawn value of 8) than clams. You could try as low as 1 if you wanted to, to see if that makes a difference.

**Comment by noobanidus** [comment]
As there's been no further updates or feedback on this issue, I'm going to close it.
