### ISSUE TITLE
Deer dont breed with wheat in Valhelsia 3 mod 3.3.0

### ISSUE THREAD

**Issue by CERIBES** [MysticMods/MysticalWorld#258]
Just started playing Valhelsia 3 the latest one form Curse Forge and Deer don't bread with wheat. Is there a mod conflict??

**Comment by noobanidus** [comment]
That's interesting, I wonder why that's happening. Thanks for the report, I'll try to look into it.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/FihEakA.png)

I'm not sure why it's happening, it's definitely functional as of 1.16.5's latest release (0.3.2.18)
