### ISSUE TITLE
Epic Squid advancement triggered by every food item

### ISSUE THREAD

**Issue by Cre8or** [MysticMods/MysticalWorld#26]
Consuming any kind of food will unlock the `Epic Squid!` achievement.

As this is a somewhat odd one, I suspect it could be possible that some kind of some obscure mod interaction is causing this. Let me know if you need a full mod list, and/or additional testing information.

**Versions used:**
Minecraft 1.12.2
Minecraft Forge 14.23.5.2836
MysticWorld-1.12.2-1.4.0
mysticallib-1.12.2-1.3.2
*(Roots-1.12.2-3.0.5)*

**Comment by duely** [comment]
Yeah, the syntax is ... weird and not what I expected when I wrote it and I just tested it with epic squid. Oops!
