### ISSUE TITLE
MysticalWorld structures can't generate with Terraforged (no registered SeparationSettings)

### ISSUE THREAD

**Issue by Taran-14** [MysticMods/MysticalWorld#261]
### General Information

**Describe the bug:**
Huts and barrows do not generate when using Terraforged

**To Reproduce:**
1. Have both Terraforged and MysticalWorld installed
2. Generate or load a Terraforged world
3. Try to locate a hut or barrow

**Expected behavior:**
Huts and barrows to generate like other modded structures in Terraforged.
***

### Environment Versions

**Mystic Mods Versions**
- MysticalWorld:  1.16.4-0.3.1.10

**Other Versions:**
- Terraforged: 0.2.10
- Forge: 36.1.13 
- Minecraft: 1.16.5

***

### Logging Information
latest.log provides the following warning, indicating missing SeperationSettings as the reason for the failure to generate:

[02May2021 18:53:58.127] [Render thread/WARN] [TerraForged/]: Structure [mysticalworld:barrow] does not have any SeparationSettings registered for it so we cannot generated it!
[02May2021 18:53:58.127] [Render thread/WARN] [TerraForged/]: Structure [mysticalworld:hut] does not have any SeparationSettings registered for it so we cannot generated it!
[02May2021 18:53:58.127] [Render thread/WARN] [TerraForged/]: Structure [mysticalworld:ruined_hut] does not have any SeparationSettings registered for it so we cannot generated it!

[latest.log](https://github.com/MysticMods/MysticalWorld/files/6412152/latest.log)

***

**Comment by noobanidus** [comment]
That's... weird, I was positive that it was done. I'll ask around.

**Comment by noobanidus** [comment]
Well, separation settings *are* registered for each of these in, as far as I was aware, the correct location. But...

From the information I've been able to gather, this is actually an issue on Terraforged's side which they are either unable or unwilling to fix (I can totally get that, it might involve way more work for them to fix it than it is for me to adjust for it). The place they're looking for separation settings isn't the same place Vanilla looks (for whatever reason).

Unfortunately, while there is a solution around it (thanks to TelepathicGrunt of Repurposed Structures), it's actually a bit of a pain and requires some manipulations that I want to test thoroughly in both a dev environment and in a testing environment.

Thus, I'm not sure when I'm going to be able to release it, but I'll try to keep you updated.
