### ISSUE TITLE
[1.12.2] Crash at startup.

### ISSUE THREAD

**Issue by Z-Tunic** [MysticMods/MysticalWorld#262]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 7
Baubles-1.12-1.5.2
jei_1.12.2-4.16.1.302
mysticallib-1.12.2-1.10.0
mysticalworld-1.12.2-1.9.6
Patchouli-1.0-23.6
Roots-1.12.2-3.0.34
Thaumcraft-1.12.2-6.1.BETA26

Report:
https://pastebin.com/k629mexR

----------

Crashes at startup. The report mentions a missing class for the Thaumcraft aspects, even though thaumcraft is already installed.

**Comment by noobanidus** [comment]
This is fixed in 1.9.8 after a hicup with 1.9.7. Should be on CurseForge now.
