### ISSUE TITLE
[Potential mod conflict, 1.16.5] Squids don't drop raw squid.

### ISSUE THREAD

**Issue by ArmageddonX430** [MysticMods/MysticalWorld#264]
### General Information

**Describe the bug:**
Squids don't drop raw squid.

**To Reproduce:**
1. Stab squid with sword.
2. No raw squid.

**Expected behavior:**
Raw squid.

***

- Version: 0.3.1.10
- Forge: 36.1.16
- Minecraft: 1.16.5

***

### Additional Information
The loot json for squid is titled squid_inject.  All the other loot jsons are just the name of the animal, like beetle and deer.

**Comment by noobanidus** [comment]
Are you running any other mods? It is not a guaranteed chance to get raw squid.

**Comment by MoonMoonShark** [comment]
> o

i'm running the server @ArmageddonX430 is on. we're using a custom modpack (https://www.curseforge.com/minecraft/modpacks/the-lighthouse).

we're also using Simple Farming (https://github.com/cweckerl/simplefarming/issues) which i believe adds in a form of calamari. i wonder if that is causing an issue?

**Comment by noobanidus** [comment]
Do you have any more information about this? I've been playing Mystical World's latest version in a light server and I've been getting raw squid.

**Comment by MoonMoonShark** [comment]
apologies for the delay. thank you for your patience. i will be doing our monthly server updates next weekend. i'll be sure to test for this.

**Comment by MoonMoonShark** [comment]
i finally got a chance to test. they still don't seem to be dropping, but i think it's a conflict with Simply Farming. i need to remove that mod to confirm, but it seems that it has also caused problems with Farmer's Delight items not dropping. will test and report back. thank you for your patience, and all of your hard work! i appreciate everything you do!

**Comment by noobanidus** [comment]
That is strange! Let me know if disabling Simple Farming works. This bug might need to be referred back to them.

**Comment by noobanidus** [comment]
Did you get a chance to test Simple Farming?

**Comment by MoonMoonShark** [comment]
today i made a clean copy of the world, new map, and the only mods installed are Oh the Biomes You'll Go, Mystical World, and Patchouli. i made a puddle with a squid spawner in the middle. killed about two dozen squids and didn't get anything but ink.

**Comment by MoonMoonShark** [comment]
today i made a completely fresh install of the server. entirely new world, with nothing in it but mystical world and patchouli. put a squid spawner in a puddle, so i could easily kill a bunch. got squid parts on the first two i killed. will do more testing to determine at what point they stop working.

**Comment by noobanidus** [comment]
Okay, I'm going to mark this as just a mod conflict and close it.

**Comment by MoonMoonShark** [comment]
i finally figured out where the conflict was, after spending the day troubleshooting. it wasn't Simple Farming after all! it was in the last place i would have expected, and i'm actually grumpy about it being so stupid. it was a data pack i had plugged in to make mobs drop their heads more often. that's it. once i took that out, everything worked fine. i'm so so sorry. i am banging my head on the desk over this. thank you again for your patience, and all of your hard work.

**Comment by noobanidus** [comment]
No worries! I'm glad it was something simple like that. :)
