### ISSUE TITLE
Is this a Fabric mod? Because CurseForge says it is

### ISSUE THREAD

**Issue by mj717** [MysticMods/MysticalWorld#265]
So, this mod is marked as a Fabric mod on CurseForge. I got super excited when I saw it (because I can only play with Fabric and this mod looks awesome), but then I realized that only the latest release is marked as being for Fabric. I'm guessing that this is a Forge mod whose mod loader was incorrectly labelled. So yeah, just a heads up on that!

**Comment by noobanidus** [comment]
My bad, I have a hand tremor that unfortunately makes clicking on the right selection in the dropdown box painful. I'm going to switch to just clicking it and hitting the End key from now on when uploading Forge mods. Apologies!

(It's fixed on CurseForge.)
