### ISSUE TITLE
Fox Breeding

### ISSUE THREAD

**Issue by KienKse** [MysticMods/MysticalWorld#266]
### General Information

**Describe the bug:**
A silver fox when breeded the new one cant be tamed. Even when are adult. 

**To Reproduce:**
1. First Step
Breed two Silver foxes
2. First Step
Let the baby grow, or just try to feed it
3. First Step
Cant tame the new silver fow

**Expected behavior:**
can tame the new silver fox

***

### Environment Versions
**Other Versions:**
- Minecraft:
1.16.5

**Comment by noobanidus** [comment]
The silver foxes will only breed when tamed; the resulting offspring of the two tamed foxes will be automatically tamed based on whichever fox was its "parent".

So, if you are the owner of both foxes, the child should be tamed to you. With mixed parents it's a 50/50. 

I might look at re-doing the breeding code, it's kind of outdated and mostly a port of the 1.12 system.

**Comment by KienKse** [comment]
I was checking the Entity class and the new adult fox it has only 10 life points maybe some conditional there.
And cant be tammed
