### ISSUE TITLE
Part of the key is the same

### ISSUE THREAD

**Issue by magcicada** [MysticMods/MysticalWorld#27]
Part of the key is the same,such sa the key`item.silver_dust.name` is the same as it of `Tiny Progressions` ,it will cause the translation get errors.I think it should add modid to the key to distinguish,thanks.
![2019-08-11 134819](https://user-images.githubusercontent.com/45464670/62830278-fe2f0780-bc3e-11e9-832f-81cab3506e0d.png)
![2019-08-11 135010](https://user-images.githubusercontent.com/45464670/62830279-fff8cb00-bc3e-11e9-9863-f108fde01e3c.png)
It will cause the translation of the key to be covered.
![2019-08-11_14 00 47](https://user-images.githubusercontent.com/45464670/62830386-a2fe1480-bc40-11e9-93d4-b73d4d42197b.png)
![2019-08-11_13 59 59](https://user-images.githubusercontent.com/45464670/62830387-a4c7d800-bc40-11e9-9cd0-e8d061f25cbd.png)

**Comment by duely** [comment]
I'm not really sure how this causes conflict, as they are both powdered silver. Surely the translation would be identical?

**Comment by magcicada** [comment]
This key`item.silver_dust.name` is the same as lightgray glowstone dust of tiny progressions,so the translation will be covered by translation of lightgray glowstone dust.

**Comment by duely** [comment]
I'd suggest that Tiny Progression's naming here is problematic, as ours is literally silver dust and the translation key is the one automatically generated by Minecraft. I'm not sure how much effort it would take for the library to be able to support it, but at the same time I'd be concerned about changing our name when ours is literally ***silver dust*** (and the ore dict key is dustSilver).

**Comment by 3TUSK** [comment]
See also:

 * HellFirePvP/ModularMachinery#94 and marcin212/Zetta-Industries#77
 * elytra/BetterBoilers#5 and jaquadro/StorageDrawers#611

The recommended practice is to always add modid into translation key, even if they are referring to items with the same meaning.

**Comment by duely** [comment]
@3TUSK Sure, but Tiny Progression's silver dust is referring to something else entirely different (grey-coloured glowstone) rather than actual silver dust. I feel like the onus should be on them to change it -- not us.

**Comment by duely** [comment]
If Tiny Progressions won't change their translation key, please open a new issue for this.
