### ISSUE TITLE
Blame report: ConfiguredFeature not registered properly (related to stonepetals)

### ISSUE THREAD

**Issue by Febilian** [MysticMods/MysticalWorld#272]
### General Information

**Describe the bug:**
I am assuming that something related to recent stonepetal changes might be causing this? Whatever is going on, it is messing with an alarming amount of biomes(mostly vanilla mountainy biomes, but also various other mod biomes with exposed stone on their surface)

***

### Environment Versions
**Mystic Mods Versions**
- Mystical World 0.3.2.16

**Other Versions:**
- Forge: 36.2.0
- Minecraft: 1.16.5

***

### Logging Information
**Blame Report:**
https://gist.github.com/Febilian/5b119d69fcee89e97b6a2623ffe26428

**Comment by noobanidus** [comment]
That's odd, the features should be registered on-the-fly once the dimensional placement is applied. It's possible I missed a step.

**Comment by noobanidus** [comment]
(For the record, this is a minor issue; registering configured features is good practice, but only essentials for certain mods/methodologies.)

**Comment by Febilian** [comment]
I mean, I've seen firsthand how unconfigured features can flat out stop the loading of features of any other mods that load after them. Did something change in Forge to fix that in the past few months?

**Comment by noobanidus** [comment]
It depends on the context, really. If there are red error messages with "unable to load json" then yeah, it's can definitely be a problem as it stops loading the rest of the biome.

**Comment by noobanidus** [comment]
Ahah! I was actually registering the properly configured feature but failing to update the reference, so it was place the raw, original configured feature (without the dimensional placement), hence this issue.

Should be fixed in the next release.
