### ISSUE TITLE
Lead armor high knockback resistance

### ISSUE THREAD

**Issue by ChiefLogan3010** [MysticMods/MysticalWorld#273]
Lead armor continues to have very high knockback resistance. I notice a previous issue where it's supposedly been fixed but in the latest version it seems to still be too high (https://github.com/MysticMods/MysticalWorld/issues/241). Each piece of armor has +20 knockback resistance, I'm assuming this is too high by a factor of 10.

mysticalworld-1.16.5-0.3.2.17.jar

- Forge: 36.2.0
- Minecraft: 1.16.5
- Modpack (if available): custom pack

**Comment by noobanidus** [comment]
I'm not sure what's happened here, in b997c59fd322f13 I reduced the knockback to 0.01 which in theory should be 10%. I'll need to compare with other knockback resistant pieces -- thanks for the report!

**Comment by noobanidus** [comment]
I'm really confused as to why this is happening. Comparing it to Netherite which is 0.1... this is confusing.

**Comment by noobanidus** [comment]
Ahah! It has to do with the default knockback resistance. I've managed to fix it.
