### ISSUE TITLE
Soft obsidian blocks stick to slime and get pushed by pistons

### ISSUE THREAD

**Issue by TheRealWormbo** [MysticMods/MysticalWorld#275]
### General Information

**Describe the bug:**
Unlike all vanilla blocks with some kind of obsidian relation (e.g. (crying) obsidian block, ender chest, enchanting table), soft obsidian and its derived blocks introduced by Mystical World will actually stick to slime blocks as those are moved, and can also directly be pushed and pulled by pistons.

**To Reproduce:**

1. Place a sticky piston.
2. Place e.g. a obsidian slab in front of the piston.
3. Activate the piston with a redstone signal, then deactivate it. The soft obsidian slab will be pushed and pulled accordingly.

**Expected behavior:**

* A piston should be unable to extend if an obsidian-like block is in the way.
* A slime/honey block structure should not be able to move if an obsidian-like block is in the way.
* A retracting sticky piston or moved slime/honey block structure should not pull along any obsidian-like blocks adjacent to any of its sticky sides.

***

### Environment Versions

**Mystic Mods Versions**

- Mystical World: 0.3.2.16

**Other Versions:**
- Forge: 36.2.0
- Minecraft: 1.16.5
- Modpack (if available): The Phoenix's Assorted Goodies

***

### Additional Information
**Additional context (optional):**

To be fair, I'm not sure if soft obsidian is supposed to not be non-sticky and unmovable, but since its behavior is essentially the default block behavior, I opted to assume it's simply an oversight.

**Comment by noobanidus** [comment]
That's definitely a fault on my part! I'll add it to the roadmap for the next release.
