### ISSUE TITLE
[1.16] Copper is not classified as $ore

### ISSUE THREAD

**Issue by BjornTjockPals** [MysticMods/MysticalWorld#277]
Copper Ore is not in $OreDictionary as other ores, you can see this in JEI by searching `@mystical  $ore`
It causes problems with UniDict and InstantUnify when trying to merge ores from mulitples mods.
Please fix that :)

**Comment by noobanidus** [comment]
This is actually fixed, I just haven't had a chance to do a new release yet. I'll look into doing it today.
