### ISSUE TITLE
[1.16.5] Enderminis spawn without requiring blocks

### ISSUE THREAD

**Issue by faeldray** [MysticMods/MysticalWorld#280]
Version: 1.16.5-0.3.3.19

Enderminis spawn in the air and fall into the void to die (or just float there?)

![2021-10-02_02 01 26](https://user-images.githubusercontent.com/967709/135707524-2317e944-279d-42f5-bfc2-a0d77882a3d6.png)

**Comment by noobanidus** [comment]
That's ... not meant to happen.

**Comment by faeldray** [comment]
Thanks for getting that fixed so quickly!
