### ISSUE TITLE
Mystical World (mysticalworld) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by PhweeDev** [MysticMods/MysticalWorld#281]
Hello,

I'm using the latest version of Mystical World (0.3.4.20) and I keep getting the load-registries event phase fail. Is there something I'm forgetting to do? Or is this an error on your part?

-Phwee
[crash-2021-10-03_10.37.39-fml.txt](https://github.com/MysticMods/MysticalWorld/files/7273895/crash-2021-10-03_10.37.39-fml.txt)
[debug.log](https://github.com/MysticMods/MysticalWorld/files/7273897/debug.log)
[latest.log](https://github.com/MysticMods/MysticalWorld/files/7273899/latest.log)

**Comment by Pepelespooder** [comment]
Agreed I have the exact same error https://gist.github.com/Pepelespooder/ff8e33c2f830bfc05d9257930007d122

**Comment by noobanidus** [comment]
That's strange, looking into it!

**Comment by noobanidus** [comment]
Ah, it appears as though I've been bit by the same bug I've warned people about when updating to mojmap. I'll do a new release presently.

**Comment by noobanidus** [comment]
Hopefully this is fixed, @Pepelespooder @Phweeeee if you could confirm that 0.3.4.21 works now?

**Comment by Pepelespooder** [comment]
Can confirm It seems to work now

**Comment by PhweeDev** [comment]
It is confirmed to be working. Thanks for being on it! Sorry for not replying btw, I'm not on GitHub much
