### ISSUE TITLE
Soft obsidian can be doubled... sort of a dupe

### ISSUE THREAD

**Issue by frakier** [MysticMods/MysticalWorld#283]
Describe the bug
Soft obsidian can be doubled... sort of a dupe... two obsidian and two of stone give you four soft obsidian.
This could be the side effect of some mod adding tags but I'm not sure. Seems like it was not intended though.
Guess you could call it some kind of equivalent exchange but it does make some really expensive recipes very cheap.

To Reproduce
[andesite for example][soft obsidian]
[soft obsidian][andesite for example]

gives four [soft obsidian]

Expected behavior
well, guessing this recipe should not exist

Screenshots / Scripts / Logs
Please add your logs and scripts (if applicable).

Versions (please complete the following information):

    Minecraft: 1.16.5
    Forge: 36.2.2
    Mystical World: 0.3.4.21

Modpack: Valhelsia 3-3.4.2a & 3-3.4.4

**Comment by noobanidus** [comment]
That's an issue on my part, I'll need to come up with some sort of "tag excluding" recipe.
