### ISSUE TITLE
[Feature Request] Armor Durability Config

### ISSUE THREAD

**Issue by Reshy** [MysticMods/MysticalWorld#286]
Hello, I was going through the configs and noticed there was no settings for the durability of the mod's armors.  Is it possible to add that as a feature on the config file?

**Comment by noobanidus** [comment]
I'll consider this if there's no way in KubeJS or CraftTweaker to adjust durability.

**Comment by Davoleo** [comment]
Afaik, you can do it with CraftTweaker with [this method](https://docs.blamejared.com/1.16/en/vanilla/api/items/IItemStack#g-withdamage)
