### ISSUE TITLE
Suggestion ( MC 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [MysticMods/MysticalWorld#311]
To make Mystical World independent of Patchouli mod. this is because of this crash:
https://paste.ee/p/p6NoE

**Comment by noobanidus** [comment]
Alternately, you could delete the copy of Patchouli you have, which appears to have been corrupted, and try installing it again.

**Comment by Kasia1403** [comment]
Sorry, but I've done it moment a go, but it is still the same and if You want to know this happends during pre-initialization stage.

**Comment by Kasia1403** [comment]
debug.log

https://paste.ee/p/iSYTI

**Comment by noobanidus** [comment]
Hm, that's strange. It still appears that there is a corrupt zip file -- which means there's a corrupt jar somewhere. I'd suggest posting on the Patchouli discord; I've never experienced this issue or even seen it before.

Unfortunately, removing the dependency is not currently an option.

**Comment by Kasia1403** [comment]
And what if Patchouli on it's own when installed without other mod does not give this crash ?

**Comment by noobanidus** [comment]
I'd recommend checking all your asset packs and all your mods can be opened in something like `7zip` without it crashing.

The section of code in the crash report is Patchouli attempting to open another mod (or an asset pack or something similar), where **that specific file** is incomplete or somehow corrupted. Specifically, `zip END header not found` -- which means that the *end* of the zip file doesn't exist or wasn't filled in properly.

> And what if Patchouli on it's own when installed without other mod does not give this crash ?

If there are no other mods, then there are no other files for Patchouli to try opening. Therefore, the crash wouldn't occur.

Again, the crash is not caused by Patchouli, but by one of the files (either a mod or an asset pack or something similar) not having been completely downloaded.

Failing that, this isn't something I've ever seen before, and Mystical World has been on this version on 1.12 for quite some time. Thus, the most likely answer here is that it's a specific mod or a specific file in your set-up that's causing the problem.

**Comment by Kasia1403** [comment]
@noobanidus So do You mean that it is something wrong with Mystical World mod ?

**Comment by Kasia1403** [comment]
Redownloaded Mystical World and Mystical Lib and still the same.

**Comment by noobanidus** [comment]
> So do You mean that it is something wrong with Mystical World mod ?

No.

Patchouli opens all mod files and searches them for a "books.json" file. For whatever reason, **one of the mods that is loaded** is missing something that is causing the error. I don't know which file.

I'd recommend reaching out for help on the Modded Minecraft discord or reddit, as this isn't an issue with Mystical World, or Mystical Lib, and I can't help you any further.

**Comment by Kasia1403** [comment]
Could You write me a link to this Modded Minecraft discord ?

**Comment by noobanidus** [comment]
https://discord.gg/moddedmc is the one from the r/feedthebeast subreddit.

**Comment by noobanidus** [comment]
There's also https://discord.mcmoddev.com/

**Comment by Kasia1403** [comment]
Sorry, but Discord people didn't help.

**Comment by Kasia1403** [comment]
"name": "mysticalworld.guidebook.name",
	"advancement_namespaces": [
		"mysticalworld"
	],
	"creative_tab": "mysticalworld",
	"advancements_tab": "mysticalworld",
	"landing_text": "mysticalworld.guidebook.landing_text",
	"book_texture": "mysticalworld:textures/gui/book.png",
	"filler_texture": "mysticalworld:textures/gui/patchouli/book_filler.png",
	"model": "mysticalworld:guidebook",
	"version": 1,
	"show_progress": false,
	"macros": {
		"$(info)": "$(thing)$(bold)$(t:Important Detail)[!]$()",
		"$(warning)": "$(#f00)$(bold)$(t:Warning)[!]$()"
	}
}

Is here everything OK ?

**Comment by noobanidus** [comment]
It should be correct. It occurs to me now that I can compile a version of Patchouli which logs each mod as it works on it; that way, when you get the error, you can check the log file to see which mod was being worked on -- that should allow you to identify which file isn't functioning properly.

You'll need to rename this file from `.jar.zip` to `.jar` and then replace your `Patchouli-VERSION.jar` with this one
[Patchouli-1.0-23_zip_debug.jar.zip](https://github.com/MysticMods/MysticalWorld/files/8477990/Patchouli-1.0-23_zip_debug.jar.zip)
.

**Comment by Kasia1403** [comment]
How to rename it ?

**Comment by Kasia1403** [comment]
I think I don't understand this. What should I do ?

**Comment by noobanidus** [comment]
> I think I don't understand this. What should I do ?

1. Remove the Patchouli mod from your mods folder.
2. Click on the link to download the file.
3. Rename the file and remove the ".zip" from the end.
4. Put the new file into your mods folder.
5. Upload your latest.log file when it crashes

**Comment by Kasia1403** [comment]
So it's still crashing. 

latest.log

https://paste.ee/p/Mw3Vr

**Comment by Kasia1403** [comment]
Yes ! I finally found it ! This mod is Not Enough Cats. But it is not on CurseForge. It's on www.9minecraft.net sadly. Is this mod the same as Not Enough Pets ? Because Not Enough Pets is on CurseForge and looks similar to Not Enough Cats.

**Comment by noobanidus** [comment]
I have no idea, sorry, but at least you know what's responsible.

**Comment by Kasia1403** [comment]
It looks like somebody added Not Enough Pets to www.9minecraft.net and renamed to Not Enough Cats. The mods look very similar.

**Comment by Kasia1403** [comment]
@noobanidus What if a mod ( nevermind if Your or others ) is available only on 9minecraft ? For example Plant Mega Pack is only on 9minecraft. Its author site is down.
