### ISSUE TITLE
Causing TPS lag on Server

### ISSUE THREAD

**Issue by n0itLT** [MysticMods/MysticalWorld#314]
I don't know why; however, I would get these crazy spikes once in a while (not fps drops) but server lags. I have the spark link here 
To see if you can help me find what's wrong?
https://spark.lucko.me/XwUZRQSFOn

**Comment by noobanidus** [comment]
a) The version of Spark you're using is outdated according to the Spark profile itself.

b) I literally have no idea what's going on with your profile. You appear to be using [MCMT](https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading), which has specific recommendations on bug-fixing. 

c) Looking at the collated entries, the only time where Mystical World even pops up is: ![](https://i.imgur.com/WMoBJNU.png)

This is a pretty insignificant contribution and isn't likely to be causing your TPS issues.

If you can replicate this without MCMT, please file another issue.
