### ISSUE TITLE
Passive mobs spawning

### ISSUE THREAD

**Issue by DoctorMage** [MysticMods/MysticalWorld#315]
Passive mobs spawning in peaceful and normal difficulty

Passive mobs do not seem to respawn when the followings mods are involved
After doing /kill @e in both difficulties after loading some chunks passive mobs will not spawn back
This was an issue originally found in another modpack but narrowed down to 7 mods these 3 are confirmed to be the source of the issue

Forge Version
36.2.33

Mods invovled
Aquaculture-1.16.5-2.1.22
fins-1.6.2.jar
mysticalworld-1.16.5-0.3.6.27

(xaeros is just so i dont have to play spot the mob)
Xaeros_Minimap_22.5.0_Forge_1.16.5
XaerosWorldMap_1.20.6_Forge_1.16.5

With mystical world disabled mobs were respawning after /kill @e in both difficulties

**Comment by noobanidus** [comment]
a) `/forge entity list` will give you a better idea of what mobs have and haven't respawned.
b) Have you confirmed this with *just* Mystical World?

The mod itself doesn't do anything special to spawning so I'm at a loss as to how Mystical World could be disabling passive mob spawns.

**Comment by DoctorMage** [comment]
Well i'm assuming its clashing with one of the other mods but that command is insanely helpful i've doing some test with just mystical world and mobs are spawning just fine
[debug.log](https://github.com/MysticMods/MysticalWorld/files/8550609/debug.log)
[latest.log](https://github.com/MysticMods/MysticalWorld/files/8550610/latest.log)

**Comment by DoctorMage** [comment]
peaceful - https://youtu.be/7Kn7MuIVFhg
normal - https://youtu.be/u2ii5MP6SwQ
[latest.log](https://github.com/MysticMods/MysticalWorld/files/8550644/latest.log)
[debug.log](https://github.com/MysticMods/MysticalWorld/files/8550646/debug.log)

**Comment by DoctorMage** [comment]
So i think their was an oversight in one of my test aplogies but the true culprit of the issue has been found to be alex's mobs
