### ISSUE TITLE
Crash with Nothirium and RenderLib.

### ISSUE THREAD

**Issue by Kasia1403** [MysticMods/MysticalWorld#317]
[crash-2022-05-24_16.19.13-client.txt](https://github.com/MysticMods/MysticalWorld/files/8763657/crash-2022-05-24_16.19.13-client.txt)

**Comment by noobanidus** [comment]
This is a Minecraft class that's failing to load from Minecraft Forge code.

As far as I can tell, it has nothing to do with Mystical World.

**Comment by Kasia1403** [comment]
I think that was because Entity Culling in my modpack was outdated.
