### ISSUE TITLE
[1.18.2]Errors when creating new world

### ISSUE THREAD

**Issue by IAnon** [MysticMods/MysticalWorld#318]
When creating a new world with the new 0.4.7.28 version for 1.18.2 I get the "Errors in currently selected datapacks prevented the world from loading." message along with 2 errors in the log when attempting to create a new world.
Using Forge 40.1.54

Errors: https://pastebin.com/5b3MdHs8

Full log: [latest.log](https://github.com/MysticMods/MysticalWorld/files/9056338/latest.log)

**Comment by MoonMoonShark** [comment]
not sure if it helps, but i'm also having this issue. "mysticalworld:quicksilver_ingot does not exist"

Full Log: [latest.log](https://github.com/MysticMods/MysticalWorld/files/9057363/latest.log)
Debug Log: [debug.log](https://github.com/MysticMods/MysticalWorld/files/9057365/debug.log)

I am trying to add it to "The Lighthouse" modpack
https://www.curseforge.com/minecraft/modpacks/the-lighthouse

Mystical World: mysticalworld-1.18.2-0.4.7.28.jar
Minecraft: 1.18.2
Forge: 40.1.54

**Comment by noobanidus** [comment]
It looks like a compatibility recipe from another mod is failing to load. @IAnon, could you post a list of the mods you were trying to launch with?

**Comment by Prof-Mole** [comment]
Hello, I was having the same problem but narrowed it down to the Create mod having compat files for mystical world quicksilver. As mystical world doesn't have quicksilver in the 1.18.2 version, I deleted the files from Create and now it works. Sorry for rambling, I'm very new to this.

**Comment by IAnon** [comment]
Sorry for the late reply but it does look like create is the culprit as Prof-Mole said, disabling it makes mystical world work.
Here is my mod list if still relevant.
https://pastebin.com/uFXpnaTb

**Comment by MoonMoonShark** [comment]
great job, team! excellent hunting!
