### ISSUE TITLE
Minecraft Crashing due to Mystical World Mod

### ISSUE THREAD

**Issue by Aiizaa** [MysticMods/MysticalWorld#319]
I'm playing with Forge version 1.12.2 and my game keeps crashing when initializing, cause: Mystical World Mod.
[crash-2022-07-06_12.57.56-client.txt](https://github.com/MysticMods/MysticalWorld/files/9057103/crash-2022-07-06_12.57.56-client.txt)

**Comment by noobanidus** [comment]
You need to update your versions of Mystical World and/or MysticalLib to the latest available.
