### ISSUE TITLE
Feeding foxes causes crash

### ISSUE THREAD

**Issue by LukeGi** [MysticMods/MysticalWorld#33]
To reproduce, feed a tamed fox an apple while in survival mode. The apple's item stack must contain only 1 apple.
I think it is caused by you shrinking the stack before casting it's item to ItemFood here: https://github.com/MysticMods/MysticalWorld/blob/master/src/main/java/epicsquid/mysticalworld/entity/EntityFox.java#L238-L242

**Comment by duely** [comment]
Fixed! Thanks for the heads up and sorry for the delay.
