### ISSUE TITLE
JER 1.12.2 Conflict

### ISSUE THREAD

**Issue by dimensionmaster20** [MysticMods/MysticalWorld#336]
I wanted to have mystical world on enigmatica 2 expert, but for some reason it keeps conflicting with JER.|
When I remove JER it works fine.
Crash Log:
https://pastebin.com/pZKFenUf

**Comment by noobanidus** [comment]
This is actually a conflict with Just Enough Resources and Stellarium/Stellars.

JER is creating a fake client world for its purposes and that other mod is attempting to create a capability for that level, but that is not compatible with JER's fake client world for some reason.
