### ISSUE TITLE
Bug? I am having an owl infestation XD

### ISSUE THREAD

**Issue by SirAron111** [MysticMods/MysticalWorld#34]
![2019-08-19_22 03 28](https://user-images.githubusercontent.com/39855956/63295942-346b2780-c2ce-11e9-88d3-ce6482d54782.png)
![2019-08-19_22 03 35](https://user-images.githubusercontent.com/39855956/63295944-346b2780-c2ce-11e9-8189-07c5ea9a9895.png)
i didnt change any configs just updated to get owls well you could say i got what i wanted just a bit much XD

**Comment by duely** [comment]
That's really strange. How is it in other biomes? It's just using very similar default values to everything else so I'm not sure why you're getting so many.

**Comment by SirAron111** [comment]
Maybe it was just a random thing to happen on world generation of the biome from biomes o plenty in the lavender field since nearly no other mob can spawn on the lavender if they need to spawn on ground. Are the owls flying mobs like bats? So they can spawn in air if they are literally the only thing that can spawn they will fill the spawn cap. Only happened in this biome so far.

**Comment by duely** [comment]
Okay, so it's definitely biome-specific. That's interesting. I'm not really sure there's anything I can do about it except specifically restricting them from spawning in that biome...

**Comment by duely** [comment]
(I imagine any other air-spawning entities will have the same problem though.)

**Comment by SirAron111** [comment]
I turned them down to the lowers value possible still some spawning not all that many anymore. Ye I think it does happen with all mobs that spawn in air but in the overworld there aren’t many mobs that fly mostly just bats and since they spawn in caves where caps are filled with normal mobs they never cause this problem (minecraft spawning isn’t the best not your fault)

**Comment by duely** [comment]
No worries! I just can't really think of any specific fixes for it...

**Comment by Meatshackles** [comment]
don't know if this is related or not but when i set owl spawning to false they still are spawning

**Comment by duely** [comment]
Thanks @Meatshackles I've opened a separate issue for that, #35

**Comment by duely** [comment]
There doesn't appear to be any way for me to specifically blacklist the owl from spawning in that biome, I think it might just be an unfortunate side-effect.
