### ISSUE TITLE
Fences Display Incorrectly in the Inventory

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#42]
Minecraft v1.12.2
Forge v14.23.5.2838
Mystical World v1.4.3

Fences that are in the inventory or JEI displays incorrectly, as seen in the image below.
![2019-08-21_21 38 50](https://user-images.githubusercontent.com/12000593/64381378-ac3c9000-cff8-11e9-96b7-7a2ee5be9c32.png)

**Comment by duely** [comment]
This is a known issue with Mystical Lib. I'll add it to the known issues sticky for now. It has to do wit the baked model rendering weirdly in inventories.

**Comment by duely** [comment]
This should be resolved with the changes coming in #49
