### ISSUE TITLE
higher levels of fortune may have amethyst ore drop no gems

### ISSUE THREAD

**Issue by majijn** [MysticMods/MysticalWorld#52]
i mined around 30 ores i had saved up with fortune 5, and between 5 to 6 dropped no gems at all.

**Comment by duely** [comment]
I think this may be fixed; it would be an issue with MysticalLib if it was one at all -- the code is practically identical to how vanilla handles fortune, so I'm not really sure why it would happen like that.

**Comment by duely** [comment]
(I'm not closing this as I don't know if it's fixed or not. I'll test it in dev later today.)

**Comment by duely** [comment]
I tested this with Fortune 5 and 64 ores and got gems from all of them, so I think the recent change to Mystical Lib will fix this in the next release.
