### ISSUE TITLE
Bizarre crash involving Charred Stairs and Building Gadgets

### ISSUE THREAD

**Issue by katubug** [MysticMods/MysticalWorld#56]
Hello! I have a weird one for you today. I have already reported it to Building Gadgets here: https://github.com/Direwolf20-MC/BuildingGadgets/issues/385 as I had initially assumed the issue was on their end. However, now I'm not completely certain? I will copy over the relevant info:

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** BuildingGadgets-2.7.3, MysticWorld-1.12.2-1.4.4, mysticallib-1.12.2-1.3.7

Hi! Was playing on my multiplayer server when I shift+right clicked Mystic World's Charred Stair block with the Exchanging Gadget. My screen went completely white, stalled for a while, and then produced this crash report: https://paste.dimdev.org/azixixinul.mccrash

A second attempt produced the same issue. I switched over to singleplayer to test it out. Vanilla stairs worked fine, Immersive Engineering Stairs worked fine, Mystical World stairs produced a crash.

Later, again in multiplayer, I encountered the same crash when I was breaking the stairs with left click - without the Exchanging Gadget in my hand (it was in my hotbar though). I'm unsure if this is related, but here's an excerpt from my server console from when that last crash occurred: https://pastebin.com/kKyH11yw

And here is an excerpt from my latest.log from when I tried to replicate the left-click crash in singleplayer. I failed to do so with the left-click, but reproduced the crash with the shift-right-click again: https://pastebin.com/Sj35RhLD

**Comment by katubug** [comment]
Okay, I suspect I understand why the second crash occurred despite my not holding the Exchanging Gadget. I think my attempts to shift+click the stairs queued themselves up and after I crashed, that queue persisted. It seems to have been resolved, and it would explain why I couldn't replicate the left-click crash in singleplayer.

Anyway, I think that makes it 95% certainly not your fault, so I'll close this issue and reopen it later if necessary.

**Comment by MajorTuvok** [comment]
So It looks like that the BufferBuilder is still active after rendering your Block, which results in the dispatcher being unable to render white Glass...

**Comment by duely** [comment]
I've reopened this as it directly relates to #49 -- hopefully it won't happen as of the next release, but I'd like to keep it open for reference. 

It is... technically not our fault, because there are a lot of other rendering processes that are able to visualise our blocks. However, there's no reason for us not to use the correct systems that are more compatible with everyone else.

**Comment by duely** [comment]
This will be fixed in the next release.
