### ISSUE TITLE
Lava cats eat blaze rods with no effect -- don';t decrement stack size

### ISSUE THREAD

**Issue by duely** [MysticMods/MysticalWorld#64]

**Comment by starspunwolf** [comment]
Unsure if it would be preferable to report this here, or in a fresh issue thread, so I'm erring on the side of replying here. 

This is an issue for me as well. I'm using the latest Mystical World as of this message, version 1.7.1. When attempting to tame a lava cat, blaze rods don't seem to work. I do get the breeding hearts on occasion, but the cat never tames no matter how many attempts are made, and the blaze rods are often not used up after right clicking the cat with them.

Full mod list: https://pastebin.com/7hPv8egY

Thank you!

**Comment by noobanidus** [comment]
@starspunwolf You have to tempt them with it the same way as you would an ocelot.
