### ISSUE TITLE
Amethyst tools/weapons don't look right on third person

### ISSUE THREAD

**Issue by slard3** [MysticMods/MysticalWorld#66]
![1](https://user-images.githubusercontent.com/55768134/66627734-feae3500-ebd2-11e9-9f22-538a92a275d6.jpg)

**Comment by duely** [comment]
Is this also the case with copper & silver tools?

**Comment by slard3** [comment]
Only Amethyst looks like this, everything else is fine

**Comment by duely** [comment]
As I suspected, the Amethyst tools are using "item/generated" instead of "item/handheld".
