### ISSUE TITLE
[1.14] Squid and Deer are dropping cooked food, instead of raw 

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#69]
ie squid are dropping Calamari instead of Raw Squid
and deer are dropping Cooked Venison
sounds like some oddness with the loot tables 

tan sprouts do not have this issue (i expected they would and tested them as well)
however, i looked at the loot tables, and they don't check for smelting their drops _at all_
~~will make a separate issue for this~~ further described in #70

edit: happy issue #69 🎉

**Comment by Birgliss** [comment]
to elaborate: i am using a plain sword for this
in specific i tried the cactus sword from this mod and the bone sword from druidcraft, both unenchanted

**Comment by duely** [comment]
```json
                {
                    "entryName": "mysticalworld:venison",
                    "weight": 1,
                    "quality": 0,
                    "type": "item",
                    "functions": [
                        {
                            "function": "minecraft:furnace_smelt",
                            "conditions": [
                                {
                                    "properties": {
                                        "minecraft:on_fire": true
                                    },
                                    "entity": "this",
                                    "condition": "minecraft:entity_properties"
                                }
                            ]
                        },
                        {
                            "count": {
                                "min": 0.0,
                                "max": 2.0
                            },
                            "function": "minecraft:looting_enchant"
                        }
                    ],
                    "name": "mysticalworld:venison"
                }
```

Looking at the actual JSON for this entry (at least specifically for deer) it seems to be correct, but perhaps that's because (I think) it's identical to the 1.12.2. I'll triple-check as there may be a new way of handling conditions in 1.14.4.
