### ISSUE TITLE
Sprouts do not drop cooked food during a fire-related death 

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#70]
this issue seems to be version agnostic, originally detailed in #69
however, 1.14 does not have purple sprouts yet

since potatoes and aubergine can be cooked, it would make sense that the sprout's loot tables would check for if the mobs are on-fire during death, and drop smelted versions of the food instead
in both 1.12 and 1.14 this check does not exist

**Comment by duely** [comment]
Yes, that's definitely an oversight on my part.

**Comment by duely** [comment]
This is fixed for 1.14. It needs to be adjusted for 1.12 still.
