### ISSUE TITLE
Crash with Corail Tombstone

### ISSUE THREAD

**Issue by NillerMedDild** [MysticMods/MysticalWorld#78]
Loading up a world with `mysticalworld-1.14.4-1.6.0` and `tombstone-4.1.6-1.14.4` caused a crash, here's the report: https://gist.github.com/NillerMedDild/dcdedd714566e49245c60c32fcf75db4

Forge-1.14.4-28.1.56

**Comment by duely** [comment]
This is actually the same as #79
