### ISSUE TITLE
Crash after killing a squid

### ISSUE THREAD

**Issue by NillerMedDild** [MysticMods/MysticalWorld#79]
### Versions

Minecraft Version: 1.14.4
EquipmentTooltips-1.14.4-1.3.2+10
SilentLib-1.14.4-4.4.0+44
mysticalworld-1.14.4-1.6.0
mysticallib-1.14.4-1.5

### Expected behavior

- Killing a squid results in a dead squid.

### Actual behaviour

- Killing a squid results in a crash.

### Steps to reproduce the problem

1. Make an instance with both Mystical World and Equipment Tooltips
2. Kill a squid
3. ...
4. Profit

I suspect that this crash is caused by a bad interaction between Mystical World and Equipment Tooltips, which is why I mentioned both version further up. I have repoted this issue on both trackers.

Original report: https://github.com/NillerMedDild/Enigmatica4/issues/93
Equipment Tooltips issue: https://github.com/SilentChaos512/Equipment-Tooltips/issues/5

**Comment by duely** [comment]
Opening up the JAR that I uploaded to CurseForge, I triple-checked that the method referred to (200900_a returning an integer) is implemented, and it looks like my attempts at being clever have unfortunateley backfired.

![](https://i.imgur.com/uD0fEWY.png)

**Comment by duely** [comment]
Yes, this is definitely my problem. Release 1.6.1 presently

**Comment by NillerMedDild** [comment]
Thanks for the quick fix :)
