### ISSUE TITLE
Aubergine doesn't grow naturally

### ISSUE THREAD

**Issue by slard3** [MysticMods/MysticalWorld#81]
### General Information

**Describe the bug:**
I've spent three Minecraft days watching an aubergine field and it isn't growing by itself. It can grow with bonemeal.

### Environment Versions
forge 28.1.56

**Mystic Mods Versions**
mysticalworld-1.14.4-1.6.4
mysticallib-1.14.4-1.5

I have too many mods (143) to make a list of it, or to check one by one if it's a compat issue, but I'll test later this mod alone to see if the issue persists. I'm simply giving a heads up about this bug.

**Comment by duely** [comment]
The log attached seems to show the game being paused for several minutes, and then the time of day being changed; growth is based on random ticks, which don't happen while the game is paused, and which are entirely unrelated to game time.

Regardless, I see the source of the issue. I'll attempt to put a new release out shortly.

**Comment by slard3** [comment]
Oh, well at least I tried to test it, I'll be more careful next time. Thank you!

**Comment by duely** [comment]
It's fine, just in future you want the gamerule that controls random ticks! See [this document on the GameRule command, specifically "randomTickSpeed"](https://minecraft.gamepedia.com/Commands/gamerule). That makes ticking blocks (not tile entities), such as crops, tick much faster when you increase the value.

**Comment by duely** [comment]
1.6.5 for 1.14.4 should address this. Thanks for the report and the effort you went into to gather data!

**Comment by slard3** [comment]
Oh, understood. Thank you for fixing it so quickly! :) I'll close this now

**Comment by duely** [comment]
No worries, once I realised what it was, it was just a matter of getting a new build out -- it would've been faster had I not been in the process of converting a bunch of stuff into the new library and out of being embedded in the mod.
