### ISSUE TITLE
Config feature request

### ISSUE THREAD

**Issue by Halfdeaf** [MysticMods/MysticalWorld#85]
It would be nice to add config options for aubergine drops from grass. Form the looks of it, it drops and the same or higher rate than vanilla seeds and can be a clutter nuisance if you have other mods that add some grass drops. 

Maybe a drop rate and on/off option. Not a high priority thing but maybe worth a spot at the back of the queue :)

**Comment by duely** [comment]
Which version are you referring to? Seed drop rates are *very* hard to tune in 1.14.4, unfortunately, while in 1.12.2 they drop at half the rate of vanilla wheat seeds.

**Comment by Halfdeaf** [comment]
Sorry, referring to 1.14

**Comment by duely** [comment]
I've adjusted the spawn chance from 15% to 5%. There's not really much else I can do except make it even lower.

**Comment by Halfdeaf** [comment]
That's a big improvement already. Thanks

**Comment by duely** [comment]
Also, as a note, and it's really, really easy, you could make a data pack that just modifies the ["grass_inject.json"](https://github.com/MysticMods/MysticalWorld/blob/1.14/src/main/resources/data/mysticalworld/loot_tables/blocks/grass_inject.json)  loot table to fill it in with your own values.

**Comment by Halfdeaf** [comment]
Oh nice, thanks for the tip

**Comment by duely** [comment]
Unfortunately there's no "inject grass seeds with standard weight", so it's really difficult to work out what the balance of things should be. I'm about to make a new release that will hopefully fix things.
