### ISSUE TITLE
Infinite Durability in 1.12.2-1.4.7

### ISSUE THREAD

**Issue by kreezxil** [MysticMods/MysticalWorld#86]
**Describe the bug**
After creating a copper axe, no durability appears on the item. Using the copper axe on trees or wood does not cause durability ticks or damage to the axe. The exception to this is if you chop leaves or chop a birch tree, then a durability bar will appear and it will take damage. After attacking leaves or a birch tree, then chopping any other type of wood, the durability will still stay the same and will not reduce with each use of the axe.

**To Reproduce**
1. craft a copper axe with 2 sticks and 3 copper ingots.
2. chop any wood from the trunk of a tree, this will activate the tree feller plugin, but will cause no durability to the axe itself to be reduced.
3. Chop leaves or a birch tree, durability will appear and axe will take damage.
4. Continue to chop any other tree, no damage to axe.

**Screenshots**
n/a

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack : Major 19
 - Mod Name: Mystical Worlds
 - Mod Version: 1.1.0

**Logs**

*****No crash report****
Crash Report: N/A 
Debug Log: N/A
Latest Log: N/A

**Additional context**
Other players have reported the same issue with other items, but I can not confirm this yet.

**Comment by duely** [comment]
a) Please update to 1.5.0
b) Please replicate without the Tree Feller plug-in. I've never encountered this issue at all in the code base or while playing/play testing. The underlying code that is used for breaking logs & damaging the axe when it does so is Vanilla's, so I'm not sure how it could be an issue on our end.

**Comment by duely** [comment]
Additionally, looking at your own issue, it appears this happens with other modded items, not just our own. I'm almost entirely certain that this is an issue with your tree felling plug-in or mod. Please re-open if the issue can be replicated without it.

**Comment by kreezxil** [comment]
so tree chopper, hmmm
