### ISSUE TITLE
Pam's HarvestCraft mode for food

### ISSUE THREAD

**Issue by Blatts12** [MysticMods/MysticalWorld#87]
Add config to lower food restoration to match pam's harvestcraft nerf

**Comment by duely** [comment]
There are mods as well as mods for CraftTweaker that allow you to do this. This is an extremely niche area that might be best suited to a compatibility within Pam's or a compatibility mod between World<->Pam's; it's not something I want to implement in the base configuration as I feel that most people who would actually want the values to be configurable would configure them manually with an aforementioned addon.
