### ISSUE TITLE
Missing Textures on all ores

### ISSUE THREAD

**Issue by KireDalbo** [MysticMods/MysticalWorld#88]
### General Information

**Describe the bug:**
None of the ores from Mystical World seem to be loading in at all. All of the Ores have the missing texture texture on them.

![](https://cdn.discordapp.com/attachments/595804846700101662/643722025965191168/unknown.png)

**Expected behavior:**
I expected the textures to load in properly

***

### Environment Versions
Underground Biomes v1.12.2

**Mystic Mods Versions**

- MysticalLib: 1.12.2
- Mystical World: 1.12.2
**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5
- Minecraft: 1.12.2

**Latest Log (if necessary):**
https://gist.github.com/KireDalbo/2694f80c8fe71351dc97d68cd0e19321

**Comment by Davoleo** [comment]
looking at the log it seems that underground biomes is failing to load of mystical world ores variant textures
Ref: https://gist.github.com/KireDalbo/2694f80c8fe71351dc97d68cd0e19321#file-gistfile1-txt-L1356

**Comment by KireDalbo** [comment]
> looking at the log it seems that underground biomes is failing to load of mystical world ores variant textures
> Ref: https://gist.github.com/KireDalbo/2694f80c8fe71351dc97d68cd0e19321#file-gistfile1-txt-L1356

Do you have any idea how I can fix this?

**Comment by KireDalbo** [comment]
I figured it out, the assets folder has a capital letter but the folder it is searching for does not have a capital letter

**Comment by duely** [comment]
Ah, this is an issue I reported to Underground Biomes a week or so ago: https://github.com/Aang23/UndergroundBiomesConstructs/issues/194

I saw this posted as an issue in the comments on CurseForge but stupidly thought it was for 1.14. If I had realised it was 1.12 I would've immediately remembered this issue.
