### ISSUE TITLE
Lava Cats are Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#89]
### General Information

**Describe the bug:**

If Hwyla is installed, `entity.entity_lava_cat.name` displays above the mob instead
**To Reproduce:**

1. Install Hwyla
2. Find a Lava Cat

**Expected behavior:**

Hwyla should display Lava Cat.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: v1.7.0
- Mystical World: v1.6.6

**Other Versions:**
- Forge: v28.1.87
- Minecraft: v1.14.4
- Hwyla: v1.10.6-B67

***
![2019-11-11_19 48 35](https://user-images.githubusercontent.com/12000593/68720428-cfde0280-0574-11ea-919f-f9feab4126a3.png)

**Comment by duely** [comment]
This is an issue with HWYLA, Minecraft no longer uses ".name" in translation keys.

**Comment by WenXin20** [comment]
All other Mystical World Entities display normally though. I also have the mod [Damage Indicators](https://www.curseforge.com/minecraft/mc-mods/ama-damage-indicator), which has the same issue.

**Comment by duely** [comment]
Let me triple check instead of just relying on the syntax, it could still be an issue on my end, my apologies.

**Comment by duely** [comment]
```  "entity.mysticalworld.beetle": "Beetle",
  "entity.mysticalworld.deer": "Deer",
  "entity.mysticalworld.endermini": "Endermini",
  "entity.mysticalworld.frog": "Frog",
  "entity.mysticalworld.lava_cat": "Lava Cat",
  "entity.mysticalworld.owl": "Owl",
  "entity.mysticalworld.silkworm": "Silkworm",
  "entity.mysticalworld.silver_fox": "Silver Fox",
  "entity.mysticalworld.sprout": "Sprout",```

So this is the automatically generated stuff that's working with every other entity, I'm not sure w... wait. I know what the issue is.
