### ISSUE TITLE
Advancement textures and titles missing

### ISSUE THREAD

**Issue by ArkVeil** [MysticMods/MysticalWorld#90]
### General Information

**Describe the bug:**

Background to advancement menu is missing and so are the advancement titles.
**To Reproduce:**

1. Load world
2. Open advancements

**Expected behavior:**

There is a proper background and titles to advancements
***

### Environment Versions

Minecraft-1.14
Forge-28.1.87
**Mystic Mods Versions**

- MysticalLib: 1.7.0
- MysticalWorld:1.14-1.6.6

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues: Better Advancements (Though I have tested with and without this one. Same result)

***

### Additional Information
**Screenshots (if available):**
![image](https://user-images.githubusercontent.com/40077783/68719931-9d83d380-057b-11ea-946d-745a5045d308.png)

**Comment by duely** [comment]
Ah, yes, hopefully this'll be fixed in the next release. Some things were moved and the auto-generation missed the advancements, but I've added them back in in development.
