### ISSUE TITLE
Missing Armor Textures on Entity

### ISSUE THREAD

**Issue by ArkVeil** [MysticMods/MysticalWorld#91]
### General Information

**Describe the bug:**

When any of the armors are worn by an entity, such as a player or armor stand, it appears as a big pink/black cube
**To Reproduce:**

1. Equip any of the armor pieces

**Expected behavior:**

Armor should properly render on top of the model.
***

### Environment Versions

Minecraft-1.14.4
Forge-28.1.87
**Mystic Mods Versions**

- MysticalLib: 1.7.0
- MysticalWorld:1.14.4-1.6.6

***

### Additional Information
**Screenshots (if available):**
![2019-11-12_18 47 18](https://user-images.githubusercontent.com/40077783/68720444-3e26c300-057d-11ea-90f6-260292509d7a.png)

**Comment by duely** [comment]
Yes, this should be fixed in the next release which should hopefully be out soon.
