### ISSUE TITLE
Wet Mud Block selection box is too small

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalWorld#92]
### General Information

**Describe the bug:**

The Mud block selection box is smaller than the actual block.

**To Reproduce:**

1. Place a Mud Block
2. Observe the selection box

**Expected behavior:**

The selection box should be the same size as the block

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: v1.7.0
- Mystical World: v1.6.6

**Other Versions:**
- Forge: v28.1.87
- Minecraft: v1.14.4

***
![2019-11-11_19 49 29](https://user-images.githubusercontent.com/12000593/68720539-37944d80-0575-11ea-9841-6797877f9954.png)

**Comment by duely** [comment]
Hm, this is potentially a hold-over from when the wet mud blocks *were* actually smaller. Block generation has resulted in a full size block, however. I'm still undecided if I'll just remove the modified bounding box, or modify the size of the model...

**Comment by duely** [comment]
This has been fixed.
