### ISSUE TITLE
v1.6.6 removes the Bone > Bonemeal recipe

### ISSUE THREAD

**Issue by Shreddys** [MysticMods/MysticalWorld#93]
Like the title says, the recipe to turn bones into bonemeal disappeared after updating to 1.6.6

Is this a bug? Or is it intended?

**Comment by VulpTheHorseDog** [comment]
Saw this, but wasn't sure which mod it was. Did you test Mystical World by itself, or was it part of a pack?

**Comment by duely** [comment]
Okay, and I think I know exactly why this is happening and it bothered me a lot at the time but I couldn't think of any negative reprecussions... except for the whole *override* factor. Basically, the vanilla data generator built the recipe name based on the output, which overrides teh default vanilla.

I'll get a fix out ASAP.

**Comment by duely** [comment]
I've just done a new release for this; it should be fully resolved as I've specified a custom name for the recipe and moved it into the MysticalWorld namespace, so there should be no further conflicts.
