### ISSUE TITLE
silk thread has no use in 1.14.4

### ISSUE THREAD

**Issue by gravysamich** [MysticMods/MysticalWorld#94]
title pretty much says it all. silk thread can't be used for anything in 1.14.4.

a simple recipe to make it into normal string would fix this. i say make it so the 2 silk thread in a shapeless recipe will make a normal string.

**Comment by duely** [comment]
Part of the issue here is that Forge doesn't override vanilla recipes to use the STRING tag that it itself creates... however, I've modified these vanilla recipes and hopefully that should fix it.

**Comment by duely** [comment]
I've pushed a new update that should resolve this issue, while adding replacement recipes to use forge:string for Vanilla recipes. Any other recipes that don't accept silk thread most likely don't actually use the forge:string tag as they should, and should be reported to the mod author.
