### ISSUE TITLE
Spindle durability

### ISSUE THREAD

**Issue by Shreddys** [MysticMods/MysticalWorld#95]
When I was converting batches of silk cocoons into thread with a spindle (in order to make wool out of it) I ended up with my spindle having a durability of -91/64. It's currently unbreakable from what I can see.

**Comment by duely** [comment]
This is 1.14?

**Comment by duely** [comment]
If it is 1.14, then how recipes handle ingredients when they break is a little... strange. I'll have to test it more thoroughly and potentially hard-code in checks for broken.

**Comment by Shreddys** [comment]
Yeah. I suppose I should have mentioned, I'm playing on 1.14.4 with version 1.6.9 of MysticalWorld.

**Comment by duely** [comment]
Thanks for the clarification, I'm wondering if there isn't any itemstack check for damage/being a broken item when it comes to the crafting grid/IInventory for the crafting grid, as opposed to how it previously functioned.
