### ISSUE TITLE
Caught Exception No Class Defined with Runic Shears Capability

### ISSUE THREAD

**Issue by DecidingSpoon** [MysticMods/MysticalWorld#96]
### General Information

**Describe the bug:**
I'm trying to build a modpack with my friends based out of the 1.12.2 Direwolf modpack. When including Roots 3, Mystical Lib, Patchouli, and Mystical World, upon launch, we get an error that says there's no class defined for the Runic Shears Capability, and our launcher crashes. 

**To Reproduce:**
1. Install Roots and its cores/dependencies to Direwolf 1.12.2
2. Launch Game
3. It should crash, giving an error. 

**Expected behavior:**

No Crash, hopefully my game would launch and function properly.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.1.1
- Mystical World: 1.5.0
- Patchouli: 1.0-20
- Roots: 3.0.21

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 
- Minecraft: 1.12.2 
- Modpack (if available): Direwolf20 1.12

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

<script src="https://gist.github.com/DecidingSpoon/2e7ed3c213695a9519082adbb5a30843.js"></script>

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by duely** [comment]
As a note, your gist is incomprehensible, as it appears to have somehow managed to copy some JavaScript into it.  

Most importantly, your version of MysticalLib is six months out of date: [the latest available is 1.4.0 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/2817910). Please update that.

**Comment by duely** [comment]
Ah, I noticed that you are specifically adding it to the pack. Please note that Twitch will often fail to enforce version limits (actually, I'm not even sure they can), and if Blockcraftery or another MysticalLib-based mod is already included, then the old version is there. 

Unfortunately, I haven't been able to get the dependencies to work properly -- either because I've made a mistake in the code, or the classes are being loaded *before* it reaches the point where it goes "hey, you need XYZ version of Mystical Lib!"

**Comment by DecidingSpoon** [comment]
So I updated blockcraftery and mystical lib, installed Roots 3 and Mystical World, and I still got the same error. Not sure if there's anything else I can be doing on my end to figure it out.

**Comment by duely** [comment]
If you're still getting the same error then you do not have the latest version of MysticalLib. Please download the latest version for 1.12.2 from where I linked earlier and see if that works.
