### ISSUE TITLE
Mobs do not make sounds

### ISSUE THREAD

**Issue by RyanCR03** [MysticMods/MysticalWorld#97]
### General Information

**Describe the bug:**
All mobs with custom sounds do not make them. the sounds are in the game, but they aren't used

**To Reproduce:**
1. Spawn Any Mystical Mob
2. Listen
3. Hear Nothing

**Expected behavior:**
The mob to use the sounds...

***

### Environment Versions
1.14.4 Forge 21.1.85, Optifine HD U F4

**Mystic Mods Versions**
- MysticalLib: 1.7.0
- MysticalWorld: 1.6.9

**Other Versions:**
- Forge: 21.1.85
- Minecraft: 1.14.4

### Logging Information
log size is too big (PRO users only)

**Comment by duely** [comment]
I actually noticed this myself and I'm not sure why it's happening. It's definitely on my to-do list, but thank you for making an issue about it -- it helps me track it.

**Comment by duely** [comment]
This should be fixed in the next release.
