### ISSUE TITLE
No drops with knifes

### ISSUE THREAD

**Issue by denzuko** [MysticMods/MysticalWorld#99]
### General Information

**Describe the bug:**

Drops not working.

**To Reproduce:**
1. place a wood log or mossy cobblestone in world.
2. right click with any knife.

**Expected behavior:**
Expected to get bark from wood and moss from mossy cobblestone.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: mysticallib-1.12.2-1.3.8.jar
MysticWorld-1.12.2-1.4.4.jar
Roots-1.12.2-3.0.13.jar

**Other Versions:**
- Conflicting mod (if regarding mod integration): could be? Tested without serene seasons and still got the issue.

- Other mods you think could cause issues:
- Forge:
- Minecraft: 1.12.2
- Modpack (if available): (custom)
https://drive.google.com/file/d/1wMefdVFEzq7mCsPZK7_CyhvX_2dIe6Mh/view?usp=sharing
- Mod list:

./Clumps-3.1.1.jar
./exnihilocreatio-1.12-0.2.4.jar
./FamiliarFauna-1.12.2-1.0.11.jar
./FastLeafDecay-v14.jar
./felling-1.4.1-1.12.x.jar
./furnus-1.12.2-2.1.8.jar
./Geolosys-1.12.2-2.1.0.jar
./primitivemobs-1.2.3a.jar
./RealisticItemDrops-1.2.14.jar
./stg-1.12.2-1.2.3.jar
./1.12.2/Guidebook-1.12.2-2.9.1.s5.jar
./vaultopic-2.1.jar
./WaterStrainer-1.12-3.2.0.jar
./BetterCombat-1.12.2-1.5.6.jar
./BetterAdvancements-1.12.2-0.1.0.77.jar
./bonsaitrees-1.0.5-b77.jar
./iChunUtil-1.12.2-7.1.4.jar
./Bountiful-2.2.0.jar
./BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
./modtweaker-4.0.17.jar
./Scannable-MC1.12.2-1.6.3.24.jar
./BetterFps-1.4.8.jar
./JustEnoughCalculation-1.12.2-3.2.2.jar
./p455w0rdslib-1.12.2-2.2.156.jar
./librarianlib-1.12.2-4.19.2-release.jar
./Locks-2.2.1.jar
./MysticalAgriculture-1.12.2-1.7.5.jar
./memory_repo/net/ilexiconn/llibrary-core/1.0.11-1.12.2/llibrary-core-1.0.11-1.12.2.jar
./RecurrentComplex-1.4.8.2.jar
./Forgelin-1.8.4.jar
./mysticallib-1.12.2-1.3.8.jar
./torohealth-1.12.2-11.jar
./BiblioCraft[v2.4.5][MC1.12.2].jar
./NoMoreRecipeConflict-0.13(1.12.2).jar
./somanyenchantments+V0.4.31.jar
./NaturesAura-b8.jar
./antiqueatlas-1.12.2-4.5.0.jar
./astralsorcery-1.12.2-1.8.10.jar
./theoneprobe-1.12-1.4.28.jar
./RedstoneFlux-1.12-2.1.0.6-universal.jar
./llibrary-1.7.19-1.12.2.jar
./LeatherWorks-1.12-1.78.0.42.jar
./coroutil-1.12.1-1.2.19.jar
./Traverse-1.12.2-1.6.0-69.jar
./InitialInventory-3.0.0.jar
./BetterThanMending-1.1.2.jar
./fluxnetworks-1.12.2-4.0.12-29.jar
./randomenchants-0.1.2.jar
./Totemic-1.12.2-0.11.4.jar
./noRecipeBook_v1.2.2formc1.12.2.jar
./OpenEye-1.12.2-0.8.jar
./IvToolkit-1.3.3-1.12.jar
./BuildingGadgets-2.7.3.jar
./Draconic-Evolution-1.12.2-2.3.24.349-universal.jar
./SilentLib-1.12.2-3.0.13+167.jar
./PrimitiveCrafting+MC1.12.2+v1.3.5.jar
./terracartreloaded-1.12.2-1.2.3.jar
./Fertilization_1.12.2-1.0.4.jar
./Patchouli-1.0-16.jar
./WanionLib-1.12.2-2.4.jar
./UniDict-1.12.2-2.9.3.jar
./CraftTweaker2-1.12-4.1.19.jar
./tombstone-3.6.0-1.12.2.jar
./DimensionalDoors-3.0.9-287.jar
./arcanearchives-0.2.0.11.jar
./Morph-o-Tool-1.2-21.jar
./AutoRegLib-1.3-32.jar
./hwell-0.5.2.jar
./blockcraftery-1.12.2-1.3.1.jar
./hopperducts-mc1.12-1.5.jar
./JustEnoughResources-1.12.2-0.9.2.60.jar
./AkashicTome-1.2-12.jar
./rustic-1.1.1.jar
./MysticWorld-1.12.2-1.4.4.jar
./Cucumber-1.12.2-1.1.3.jar
./limelib-1.12.2-1.7.12.jar
./Nyx-1.1.0.jar
./SilentGear-1.12.2-0.6.7+76.jar
./rftools-1.12-7.72.jar
./hooked-1.0.3.jar
./Roots-1.12.2-3.0.13.jar
./MTLib-3.0.6.jar
./ProjectIntelligence-1.12.2-1.0.8.25-universal.jar
./wards-1.0.jar
./jei_1.12.2-4.15.0.291.jar
./BrandonsCore-1.12.2-2.4.17.208-universal.jar
./CodeChickenLib-1.12.2-3.2.3.358-universal.jar
./Triumph-1.12.2-3.18.0.jar
./xnet-1.12-1.8.2.jar
./FluidFunnel-1.12.2-1.3.0.jar
./AIImprovements-1.12-0.0.1b3.jar
./respawnablepets-1.0.5.1.jar
./CraftingTweaks_1.12.2-8.1.9.jar
./AmbientSounds_v2.3_mc1.12.2.jar
./multimob-1.0.4.jar
./valkyrielib-1.12.2-2.0.20.1.jar
./Quark-r1.6-177.jar
./tanspit-1.12.2-1.3.jar
./Baubles-1.12-1.5.2.jar
./findme-1.12.2-1.1.0-8.jar
./roughTweaks0.2.4-1.12.2.jar
./BNBGamingLib-1.12.2-2.17.6.jar
./jetif-1.12.2-1.5.1.jar
./Capsule-1.12.2-3.2.103.jar
./deepmoblearning-1.12.2-2.5.2-universal.jar
./walljump-1.12.2-1.2.3.jar
./environmentaltech-1.12.2-2.0.20.1.jar
./supersoundmuffler-1.12.2-1.0.2.10.jar
./mcjtylib-1.12-3.5.4.jar
./ToughAsNails-1.12.2-3.1.0.139-universal.jar
./strawgolem-1.3.jar
./ProjectE-1.12.2-PE1.4.1.jar
./Bloodmoon-MC1.12.2-1.5.3.jar
./InventoryTweaks-1.63.jar
./Chisel-MC1.12.2-0.2.1.35.jar
./ProjectVibrantJourneys-1.12.2-1.6.4.jar
./BNBGamingCore-1.12.2-0.11.0.jar
./SimpleStorageNetwork-1.12.2-1.7.9.jar
./SereneSeasons-1.12.2-1.2.18-universal.jar
./DeathQuotes-1.2.0-mc1.12-forge.jar
./ignitehud_1.12-b0.1.1.jar
./dwmh-1.12.2-3.1.2.jar
./Waystones_1.12.2-4.0.72.jar
./JEROreIntegration-1.12.2-1.1.0.jar
./MouseTweaks-2.10-mc1.12.2.jar
./CTM-MC1.12.2-0.3.3.22.jar

***

### Logging Information

https://gist.github.com/denzuko/7e3e0137ec0d70864782a7f25ec7544c

**Comment by duely** [comment]
Well, breaking logs with knives is how you obtain bark. I presume that some other mod is preventing the right-click action from functioning... 

However, looking at your versions, your Roots & MysticalLib are quite out of date. I believe the most recent release of Roots is 3.0.21. Try updating and let me know if you're still having issues.

**Comment by denzuko** [comment]
That did it. Though there was some entities removed but I'm guessing that's something to be expected.
